package net.sam.dcl.dbo;

// Generated 23-May-2007 22:53:40 by Hibernate Tools 3.2.0.b9

import net.sam.dcl.dbo.DboCustomCode;
import net.sam.dcl.dbo.dirty.DclCommercialProposal;
import net.sam.dcl.dbo.dirty.DclOrdListProduce;

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.*;

/**
 * DclCprListProduce generated by hbm2java
 */
@Entity
@SequenceGenerator( name = "GEN_DCL_ASSEMBLE_ID",sequenceName = "GEN_DCL_ASSEMBLE_ID", allocationSize = 1)
@Table(name = "DCL_ASSEMBLE")
public class DboAssemble implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "GEN_DCL_ASSEMBLE_ID")
	@Column(name = "ASM_ID", unique = true, nullable = false)
	private Integer id;

	@Column(name="ASM_NUMBER")
	private String number;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "USR_ID_CREATE")
	private DboUser createUser;

	@Column(name="ASM_CREATE_DATE")
	private Date createDate;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "USR_ID_EDIT")
	private DboUser editUser;

	@Column(name="ASM_EDIT_DATE")
	private Date editDate;

	@Column(name="ASM_DATE")
	private Date date;

	@Column(name="ASM_BLOCK")
	private Short block;

	@Column(name="ASM_COUNT")
	private Integer count;

	@Column(name="ASM_TYPE")
	private short type;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "OPR_ID")
	private DclOrdListProduce ordListProduce;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PRD_ID")
	private DboProduce produce;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "STF_ID")
	private DboStuffCategory stuffCategory;

	public DboAssemble() {
	}

	public DboAssemble(Integer id) {
		this.id = id;
	}

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getNumber() {
		return number;
	}

	public void setNumber(String number) {
		this.number = number;
	}

	public DboUser getCreateUser() {
		return createUser;
	}

	public void setCreateUser(DboUser createUser) {
		this.createUser = createUser;
	}

	public Date getCreateDate() {
		return createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public DboUser getEditUser() {
		return editUser;
	}

	public void setEditUser(DboUser editUser) {
		this.editUser = editUser;
	}

	public Date getEditDate() {
		return editDate;
	}

	public void setEditDate(Date editDate) {
		this.editDate = editDate;
	}

	public Date getDate() {
		return date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public Short getBlock() {
		return block;
	}

	public void setBlock(Short block) {
		this.block = block;
	}

	public Integer getCount() {
		return count;
	}

	public void setCount(Integer count) {
		this.count = count;
	}

	public short getType() {
		return type;
	}

	public void setType(short type) {
		this.type = type;
	}

	public DclOrdListProduce getOrdListProduce() {
		return ordListProduce;
	}

	public void setOrdListProduce(DclOrdListProduce ordListProduce) {
		this.ordListProduce = ordListProduce;
	}

	public DboProduce getProduce() {
		return produce;
	}

	public void setProduce(DboProduce produce) {
		this.produce = produce;
	}

	public DboStuffCategory getStuffCategory() {
		return stuffCategory;
	}

	public void setStuffCategory(DboStuffCategory stuffCategory) {
		this.stuffCategory = stuffCategory;
	}
}