package net.sam.dcl.dbo;

// Generated 23-May-2007 22:53:40 by Hibernate Tools 3.2.0.b9

import net.sam.dcl.dbo.DboCustomCode;
import net.sam.dcl.dbo.dirty.DclCommercialProposal;
import net.sam.dcl.dbo.dirty.DclOrdListProduce;

import java.math.BigDecimal;
import javax.persistence.*;

/**                                                                                  
 * DclCprListProduce generated by hbm2java
 */
@Entity
@SequenceGenerator( name = "GEN_DCL_ASM_LIST_PRODUCE_ID",sequenceName = "GEN_DCL_ASM_LIST_PRODUCE_ID", allocationSize = 1)
@Table(name = "DCL_ASM_LIST_PRODUCE")
public class DboAsmListProduce implements java.io.Serializable {

	private int id;
	private DboAssemble assemble;
	private DclOrdListProduce ordListProduce;
	private DboProduce produce;
	private BigDecimal count;

	public DboAsmListProduce() {
	}

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "GEN_DCL_ASM_LIST_PRODUCE_ID")
	@Column(name = "APR_ID", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}



	@Column(name = "APR_COUNT", precision = 15)
	public BigDecimal getCount() {
		return this.count;
	}

	public void setCount(BigDecimal count) {
		this.count = count;
	}


	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PRD_ID")
	public DboProduce getProduce() {
		return produce;
	}

	public void setProduce(DboProduce produce) {
		this.produce = produce;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ASM_ID")
	public DboAssemble getAssemble() {
		return assemble;
	}

	public void setAssemble(DboAssemble assemble) {
		this.assemble = assemble;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "OPR_ID")
	public DclOrdListProduce getOrdListProduce() {
		return ordListProduce;
	}

	public void setOrdListProduce(DclOrdListProduce ordListProduce) {
		this.ordListProduce = ordListProduce;
	}
}