package net.sam.dcl.dbo;

// Generated 23-May-2007 22:53:40 by Hibernate Tools 3.2.0.b9

import net.sam.dcl.dbo.DboCustomCode;
import net.sam.dcl.dbo.dirty.DclCommercialProposal;

import java.math.BigDecimal;
import javax.persistence.*;

/**
 * DclCprListProduce generated by hbm2java
 */
@Entity
@SequenceGenerator( name = "GEN_DCL_CPR_LIST_PRODUCE_ID",sequenceName = "GEN_DCL_CPR_LIST_PRODUCE_ID", allocationSize = 1)
@Table(name = "DCL_CPR_LIST_PRODUCE")
public class DboCprListProduce implements java.io.Serializable {

	private int id;

	private DboCustomCode customCode;

	private DclCommercialProposal commercialProposal;

	private String produceName;

	private BigDecimal price;

	private BigDecimal count;

	private BigDecimal coeficient;

	private String catalogNum;

	private String comment;

	private DboStuffCategory stuffCategory;

	private DboProduce produce;


	public DboCprListProduce() {
	}

	public DboCprListProduce(int id,
			DclCommercialProposal dclCommercialProposal, String produceName) {
		this.id = id;
		this.commercialProposal = dclCommercialProposal;
		this.produceName = produceName;
	}

	public DboCprListProduce(int id, DboCustomCode customCode,
			DclCommercialProposal dclCommercialProposal, String produceName,
			BigDecimal price, BigDecimal count, BigDecimal coeficient,
			String catalogNum) {
		this.id = id;
		this.customCode = customCode;
		this.commercialProposal = dclCommercialProposal;
		this.produceName = produceName;
		this.price = price;
		this.count = count;
		this.coeficient = coeficient;
		this.catalogNum = catalogNum;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "GEN_DCL_CPR_LIST_PRODUCE_ID")
	@Column(name = "LPR_ID", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CUS_ID")
	public DboCustomCode getCustomCode() {
		return this.customCode;
	}

	public void setCustomCode(DboCustomCode dboCustomCode) {
		this.customCode = dboCustomCode;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CPR_ID", nullable = false)
	public DclCommercialProposal getCommercialProposal() {
		return this.commercialProposal;
	}

	public void setCommercialProposal(
			DclCommercialProposal dclCommercialProposal) {
		this.commercialProposal = dclCommercialProposal;
	}

	@Column(name = "LPR_PRODUCE_NAME", nullable = false, length = 1000)
	public String getProduceName() {
		return this.produceName;
	}

	public void setProduceName(String produceName) {
		this.produceName = produceName;
	}

	@Column(name = "LPR_PRICE_NETTO", precision = 15)
	public BigDecimal getPrice() {
		return this.price;
	}

	public void setPrice(BigDecimal price) {
		this.price = price;
	}

	@Column(name = "LPR_COUNT", precision = 15)
	public BigDecimal getCount() {
		return this.count;
	}

	public void setCount(BigDecimal count) {
		this.count = count;
	}

	@Column(name = "LPR_COEFICIENT", precision = 15)
	public BigDecimal getCoeficient() {
		return this.coeficient;
	}

	public void setCoeficient(BigDecimal coeficient) {
		this.coeficient = coeficient;
	}

	@Column(name = "LPR_CATALOG_NUM", length = 50)
	public String getCatalogNum() {
		return this.catalogNum;
	}

	public void setCatalogNum(String catalogNum) {
		this.catalogNum = catalogNum;
	}

	@Column(name = "LPR_COMMENT", length = 5000)
	public String getComment() {
		return comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "STF_ID")
	public DboStuffCategory getStuffCategory() {
		return stuffCategory;
	}

	public void setStuffCategory(DboStuffCategory stuffCategory) {
		this.stuffCategory = stuffCategory;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PRD_ID")
	public DboProduce getProduce() {
		return produce;
	}

	public void setProduce(DboProduce produce) {
		this.produce = produce;
	}
}
