package net.sam.dcl.dbo;

// Generated 23-May-2007 22:53:40 by Hibernate Tools 3.2.0.b9

import java.util.HashSet;
import java.util.Set;
import javax.persistence.*;

/**
 * DboCategory generated by hbm2java
 */
@Entity
@Table(name = "DCL_CATEGORY",
			 uniqueConstraints = @UniqueConstraint(columnNames = {"CAT_ID", "PARENT_ID" }))
@SequenceGenerator( name = "GEN_DCL_CATEGORY_ID",sequenceName = "GEN_DCL_CATEGORY_ID", allocationSize = 1)
public class DboCategory implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "GEN_DCL_CATEGORY_ID")
	@Column(name = "CAT_ID", unique = true, nullable = false)
	private Integer id;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PARENT_ID")
	private DboCategory parent;

	@Column(name = "CAT_NAME", length = 100)
	private String name;

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "parent")
	private Set<DboCategory> children = new HashSet<DboCategory>();

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "category")
	private Set<DboProduce> produces = new HashSet<DboProduce>();

	public DboCategory() {
	}

	public DboCategory(String name) {
		this.name = name;
	}

	public DboCategory(int catId) {
		this.id = catId;
	}

	public DboCategory(Integer id, String name) {
		this.id = id;
		this.name = name;
	}

	public DboCategory(Integer catId, DboCategory dboCategory, String catName,
			Set<DboCategory> dboCategories, Set<DboProduce> dboProduces) {
		this.id = catId;
		this.parent = dboCategory;
		this.name = catName;
		this.children = dboCategories;
		this.produces = dboProduces;
	}

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public DboCategory getParent() {
		return this.parent;
	}

	public void setParent(DboCategory parent) {
		this.parent = parent;
	}


	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}


	public Set<DboCategory> getChildren() {
		return this.children;
	}

	public void setChildren(Set<DboCategory> children) {
		this.children = children;
	}
	public void addChild(DboCategory category) {
		category.setParent(this);
		children.add(category);
	}


	public Set<DboProduce> getProduces() {
		return this.produces;
	}

	public void setProduces(Set<DboProduce> produces) {
		this.produces = produces;
	}
	public void addProduce(DboProduce produce) {
		produce.setCategory(this);
		produces.add(produce);
	}

}
