package net.sam.dcl.dbo;

// Generated 23-May-2007 22:53:40 by Hibernate Tools 3.2.0.b9

import javax.persistence.*;

/**
 * DboCatalogNumber generated by hbm2java
 */
@Entity
@Table(name = "DCL_CATALOG_NUMBER",
       uniqueConstraints = @UniqueConstraint(columnNames = {"STF_ID", "PRD_ID"}))
@SequenceGenerator(name = "GEN_DCL_CATALOG_NUMBER_ID", sequenceName = "GEN_DCL_CATALOG_NUMBER_ID", allocationSize = 1)
public class DboCatalogNumber implements java.io.Serializable {
  @Id
  @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "GEN_DCL_CATALOG_NUMBER_ID")
  @Column(name = "CTN_ID", unique = true, nullable = false)
  private Integer id;

  @ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(name = "PRD_ID", nullable = false)
  private DboProduce produce;

  @ManyToOne(fetch = FetchType.EAGER)
  @JoinColumn(name = "STF_ID", nullable = false)
  private DboStuffCategory stuffCategory;

  @ManyToOne(fetch = FetchType.EAGER)
  @JoinColumn(name = "MAD_ID", nullable = true)
  private DboMontageAdjustment montageAdjustment;

  @Column(name = "CTN_NUMBER", nullable = false, length = 50)
  private String number;

  public DboCatalogNumber() {
  }

  public DboCatalogNumber(DboProduce dboProduce,
                          DboStuffCategory dboStuffCategory) {
    this.produce = dboProduce;
    this.stuffCategory = dboStuffCategory;
  }

  public DboCatalogNumber(DboProduce dboProduce,
                          DboStuffCategory dboStuffCategory, String ctnNumber) {
    this.produce = dboProduce;
    this.stuffCategory = dboStuffCategory;
    this.number = ctnNumber;
  }

  public DboCatalogNumber(DboProduce dboProduce,
                          DboStuffCategory dboStuffCategory, String ctnNumber, DboMontageAdjustment montageAdjustment) {
    this.produce = dboProduce;
    this.stuffCategory = dboStuffCategory;
    this.number = ctnNumber;
    this.montageAdjustment = montageAdjustment;
  }

  public DboCatalogNumber(Integer ctnId, DboProduce dboProduce,
                          DboStuffCategory dboStuffCategory, String ctnNumber, DboMontageAdjustment montageAdjustment) {
    this.id = ctnId;
    this.produce = dboProduce;
    this.stuffCategory = dboStuffCategory;
    this.number = ctnNumber;
    this.montageAdjustment = montageAdjustment;
  }


  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public DboProduce getProduce() {
    return this.produce;
  }

  public void setProduce(DboProduce produce) {
    this.produce = produce;
  }


  public DboStuffCategory getStuffCategory() {
    return stuffCategory;
  }

  public void setStuffCategory(DboStuffCategory stuffCategory) {
    this.stuffCategory = stuffCategory;
  }

  public String getNumber() {
    return this.number;
  }

  public void setNumber(String number) {
    this.number = number;
  }

  public DboMontageAdjustment getMontageAdjustment() {
    return montageAdjustment;
  }

  public void setMontageAdjustment(DboMontageAdjustment montageAdjustment) {
    this.montageAdjustment = montageAdjustment;
  }
}
 