package net.sam.dcl.dbo;

// Generated 23-May-2007 22:53:40 by Hibernate Tools 3.2.0.b9

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.*;

/**
 * DboCustomCode generated by hbm2java
 */
@Entity
@Table(name = "DCL_CUSTOM_CODE",
  uniqueConstraints = @UniqueConstraint(columnNames = {"CUS_CODE", "CUS_INSTANT"}))
@SequenceGenerator(name = "GEN_DCL_CUSTOM_CODE_ID", sequenceName = "GEN_DCL_CUSTOM_CODE_ID", allocationSize = 1)
public class DboCustomCode implements java.io.Serializable
{
  @Id
  @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "GEN_DCL_CUSTOM_CODE_ID")
  @Column(name = "CUS_ID", unique = true, nullable = false)
  private Integer id;

  @Column(name = "CUS_CODE", nullable = false, length = 10)
  private String code;

  @Column(name = "CUS_LAW_240_FLAG")
  private String law240Flag;

  @Column(name = "CUS_BLOCK")
  private String block;

  @Column(name = "CUS_DESCRIPTION", length = 500)
  private String description;

  @Column(name = "CUS_PERCENT", nullable = false, precision = 15)
  private BigDecimal percent;

  @Column(name = "CUS_INSTANT", nullable = false, length = 19)
  private Date instant;

//	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "customCode")
//	private Set<DboProduce> produces = new HashSet<DboProduce>();

  @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "customCode")
  private Set<DboCprListProduce> dclCprListProduces = new HashSet<DboCprListProduce>();

  public DboCustomCode()
  {
  }

  public DboCustomCode(int cusId, String cusCode, BigDecimal cusPercent,
                       Date cusInstant)
  {
    this.id = cusId;
    this.code = cusCode;
    this.percent = cusPercent;
    this.instant = cusInstant;
  }

  public DboCustomCode(Integer cusId, String cusCode, String cusDescription, String cusLaw240Flag, String cusBlock,
                       BigDecimal cusPercent, Date cusInstant,
                       Set<DboCprListProduce> dclCprListProduces)
  {
    this.id = cusId;
    this.code = cusCode;
    this.law240Flag = cusLaw240Flag;
    this.block = cusBlock;
    this.description = cusDescription;
    this.percent = cusPercent;
    this.instant = cusInstant;
    this.dclCprListProduces = dclCprListProduces;
  }

  public DboCustomCode(DboCustomCode customCode)
  {
    this.id = customCode.getId();
    this.code = customCode.getCode();
    this.law240Flag = customCode.getLaw240Flag();
    this.block = customCode.getBlock();
    this.description = customCode.getDescription();
    this.percent = customCode.getPercent();
    this.instant = customCode.getInstant();
  }

  public Integer getId()
  {
    return this.id;
  }

  public void setId(Integer id)
  {
    this.id = id;
  }

  public String getCode()
  {
    return this.code;
  }

  public void setCode(String code)
  {
    this.code = code;
  }

  public String getLaw240Flag()
  {
    return law240Flag;
  }

  public void setLaw240Flag(String law240Flag)
  {
    this.law240Flag = law240Flag;
  }

  public String getBlock()
  {
    return block;
  }

  public void setBlock(String block)
  {
    this.block = block;
  }

  public String getDescription()
  {
    return this.description;
  }

  public void setDescription(String description)
  {
    this.description = description;
  }

  public BigDecimal getPercent()
  {
    return this.percent;
  }

  public void setPercent(BigDecimal percent)
  {
    this.percent = percent;
  }


  public Date getInstant()
  {
    return this.instant;
  }

  public void setInstant(Date instant)
  {
    this.instant = instant;
  }

  public Set<DboCprListProduce> getDclCprListProduces()
  {
    return this.dclCprListProduces;
  }

  public void setDclCprListProduces(Set<DboCprListProduce> dclCprListProduces)
  {
    this.dclCprListProduces = dclCprListProduces;
  }

}
