package net.sam.dcl.dbo;

// Generated 23-May-2007 22:53:40 by Hibernate Tools 3.2.0.b9

import net.sam.dcl.dbo.DboUser;
import net.sam.dcl.dbo.dirty.DclDlrListProduce;
import net.sam.dcl.controller.ActionContext;
import net.sam.dcl.controller.IActionContext;
import net.sam.dcl.util.StrutsUtil;
import net.sam.dcl.util.StringUtil;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.*;

import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;

/**
 * DboDeliveryRequest generated by hbm2java
 */
@Entity
@Table(name = "DCL_DELIVERY_REQUEST")
public class DboDeliveryRequest implements java.io.Serializable {
  protected static Log log = LogFactory.getLog(DboDeliveryRequest.class);

	@Id
	@Column(name = "DLR_ID", unique = true, nullable = false)
	private Integer id;

	private DboUser userByUsrIdPlace;

	private DboUser userByUsrIdCreate;

	private DboUser userByUsrIdEdit;

	private Date createDate;

	private Date editDate;

	private Date placeDate;

	private String number;

	private Date date;

	private Short fairTrade;

	private String wherefrom;

	private String comment;

	private Short placeRequest;

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.EAGER, mappedBy = "deliveryRequest")
	private Set<DclDlrListProduce> produces = new HashSet<DclDlrListProduce>();

	public DboDeliveryRequest() {
	}

	public DboDeliveryRequest(int dlrId, DboUser dclUserByUsrIdCreate,
			DboUser dclUserByUsrIdEdit, Date dlrCreateDate, Date dlrEditDate,
			String dlrNumber, Date dlrDate) {
		this.id = dlrId;
		this.userByUsrIdCreate = dclUserByUsrIdCreate;
		this.userByUsrIdEdit = dclUserByUsrIdEdit;
		this.createDate = dlrCreateDate;
		this.editDate = dlrEditDate;
		this.number = dlrNumber;
		this.date = dlrDate;
	}

	public DboDeliveryRequest(Integer dlrId, DboUser dclUserByUsrIdPlace,
			DboUser dclUserByUsrIdCreate, DboUser dclUserByUsrIdEdit,
			Date dlrCreateDate, Date dlrEditDate, Date dlrPlaceDate,
			String dlrNumber, Date dlrDate, Short dlrFairTrade, String dlrWherefrom,
			String dlrComment, Short dlrPlaceRequest,
			Set<DclDlrListProduce> dclDlrListProduces) {
		this.id = dlrId;
		this.userByUsrIdPlace = dclUserByUsrIdPlace;
		this.userByUsrIdCreate = dclUserByUsrIdCreate;
		this.userByUsrIdEdit = dclUserByUsrIdEdit;
		this.createDate = dlrCreateDate;
		this.editDate = dlrEditDate;
		this.placeDate = dlrPlaceDate;
		this.number = dlrNumber;
		this.date = dlrDate;
		this.fairTrade = dlrFairTrade;
		this.wherefrom = dlrWherefrom;
		this.comment = dlrComment;
		this.placeRequest = dlrPlaceRequest;
		this.produces = dclDlrListProduces;
	}

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}



	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "USR_ID_PLACE")
	public DboUser getUserByUsrIdPlace() {
		return this.userByUsrIdPlace;
	}

	public void setUserByUsrIdPlace(DboUser userByUsrIdPlace) {
		this.userByUsrIdPlace = userByUsrIdPlace;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "USR_ID_CREATE", nullable = false)
	public DboUser getUserByUsrIdCreate() {
		return this.userByUsrIdCreate;
	}

	public void setUserByUsrIdCreate(DboUser userByUsrIdCreate) {
		this.userByUsrIdCreate = userByUsrIdCreate;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "USR_ID_EDIT", nullable = false)
	public DboUser getUserByUsrIdEdit() {
		return this.userByUsrIdEdit;
	}

	public void setUserByUsrIdEdit(DboUser userByUsrIdEdit) {
		this.userByUsrIdEdit = userByUsrIdEdit;
	}

	@Column(name = "DLR_CREATE_DATE", nullable = false, length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Column(name = "DLR_EDIT_DATE", nullable = false, length = 19)
	public Date getEditDate() {
		return this.editDate;
	}

	public void setEditDate(Date editDate) {
		this.editDate = editDate;
	}

	@Column(name = "DLR_PLACE_DATE", length = 19)
	public Date getPlaceDate() {
		return this.placeDate;
	}

	public void setPlaceDate(Date placeDate) {
		this.placeDate = placeDate;
	}

	@Column(name = "DLR_NUMBER", nullable = false, length = 15)
	public String getNumber() {
		return this.number;
	}

	public void setNumber(String number) {
		this.number = number;
	}

	@Column(name = "DLR_DATE", length = 19)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	@Column(name = "DLR_FAIR_TRADE")
	public Short getFairTrade() {
		return this.fairTrade;
	}

	public void setFairTrade(Short fairTrade) {
		this.fairTrade = fairTrade;
	}

	@Column(name = "DLR_WHEREFROM", length = 300)
	public String getWherefrom() {
		return this.wherefrom;
	}

	public void setWherefrom(String wherefrom) {
		this.wherefrom = wherefrom;
	}

	@Column(name = "DLR_COMMENT", length = 5000)
	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	@Column(name = "DLR_PLACE_REQUEST")
	public Short getPlaceRequest() {
		return this.placeRequest;
	}

	public void setPlaceRequest(Short placeRequest) {
		this.placeRequest = placeRequest;
	}


	public Set<DclDlrListProduce> getProduces() {
		return this.produces;
	}
	public void setProduces(Set<DclDlrListProduce> produces) {
		this.produces = produces;
	}

  @Transient
  public String getMsg_check_block()
  {
    if ( placeRequest != null && 1 == placeRequest )
      return "ask_unblock";
    else
      return "ask_block";
  }

  @Transient
  public String getFairTradeFormatted()
  {
    if (  null != fairTrade && 1 == fairTrade )
    {
      IActionContext context = ActionContext.threadInstance();
      try
      {
        return StrutsUtil.getMessage(context, "DeliveryRequests.dlr_fair_trade");
      }
      catch (Exception e)
      {
        log.error(e);
      }
    }

    return "";
  }

  @Transient
  public String getDateFormatted()
  {
    return StringUtil.dbTimestampString2appDateString(date.toString());
  }
}
