package net.sam.dcl.dbo;

// Generated 23-May-2007 22:53:40 by Hibernate Tools 3.2.0.b9

import net.sam.dcl.util.HibernateUtil;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.*;

import org.hibernate.Session;

/**
 * DclLanguage generated by hbm2java
 */
@Entity
@Table(name = "DCL_LANGUAGE")
@SequenceGenerator( name = "GEN_DCL_LANGUAGE_ID",sequenceName = "GEN_DCL_LANGUAGE_ID", allocationSize = 1)
public class DboLanguage implements java.io.Serializable {
	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "GEN_DCL_LANGUAGE_ID")
	@Column(name = "LNG_ID", unique = true, nullable = false)
	private Integer id;

	@Column(name = "LNG_NAME", nullable = false, length = 32)
	private String name;

	@Column(name = "LNG_LETTER_ID", nullable = false, length = 2)
	private String code;

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "language")
	private Set<DboUserLanguage> userLanguages = new HashSet<DboUserLanguage>();

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "language")
	private Set<DboProduceLanguage> produceLanguages = new HashSet<DboProduceLanguage>();

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "language")
	private Set<DboUnitLanguage> unitLanguages = new HashSet<DboUnitLanguage>();

	public DboLanguage() {
	}

	public DboLanguage(int lngId, String lngName, String lngLetterId) {
		this.id = lngId;
		this.name = lngName;
		this.code = lngLetterId;
	}

	public DboLanguage(Integer lngId, String lngName, String lngLetterId,
			Set<DboUserLanguage> dclUserLanguages,
			Set<DboProduceLanguage> dclProduceLanguages,
			Set<DboUnitLanguage> dclUnitLanguages) {
		this.id = lngId;
		this.name = lngName;
		this.code = lngLetterId;
		this.userLanguages = dclUserLanguages;
		this.produceLanguages = dclProduceLanguages;
		this.unitLanguages = dclUnitLanguages;
	}


	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}


	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public Set<DboUserLanguage> getUserLanguages() {
		return this.userLanguages;
	}

	public void setUserLanguages(Set<DboUserLanguage> userLanguages) {
		this.userLanguages = userLanguages;
	}


	public Set<DboProduceLanguage> getProduceLanguages() {
		return this.produceLanguages;
	}

	public void setProduceLanguages(
			Set<DboProduceLanguage> produceLanguages) {
		this.produceLanguages = produceLanguages;
	}

	public Set<DboUnitLanguage> getUnitLanguages() {
		return this.unitLanguages;
	}

	public void setUnitLanguages(
			Set<DboUnitLanguage> unitLanguages) {
		this.unitLanguages = unitLanguages;
	}

	static public class DAO {
		public static DboLanguage loadByLangCode(String langCode) {
			Session hibSession = HibernateUtil.getSessionFactory().getCurrentSession();
			return (DboLanguage) hibSession.createQuery("from DboLanguage l where l.code=:code").
					setString("code", langCode).uniqueResult();
		}

	}
}
