package net.sam.dcl.dbo;

// Generated 23-May-2007 22:53:40 by Hibernate Tools 3.2.0.b9

import net.sam.dcl.dbo.DboProduce;
import net.sam.dcl.dbo.DboLanguage;
import net.sam.dcl.util.HibernateUtil;

import javax.persistence.*;

import org.hibernate.annotations.Formula;

/**
 * DclProduceLanguage generated by hbm2java
 */
@Entity
@Table(name = "DCL_PRODUCE_LANGUAGE")
public class DboProduceLanguage implements java.io.Serializable {
	@EmbeddedId
	@AttributeOverrides( {
			@AttributeOverride(name = "prdId", column = @Column(name = "PRD_ID", nullable = false)),
			@AttributeOverride(name = "lngId", column = @Column(name = "LNG_ID", nullable = false)) })
	private ProduceLanguageId id;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PRD_ID", nullable = false, insertable = false, updatable = false)
	private DboProduce produce;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "LNG_ID", nullable = false, insertable = false, updatable = false)
	private DboLanguage language;

	@Column(name = "PRD_LNG_NAME", length = 1000)
	private String name;

	@Formula("(SELECT DCL_LNG.LNG_LETTER_ID FROM DCL_LANGUAGE DCL_LNG where DCL_LNG.LNG_ID=LNG_ID)")
	private String langCode;

	public DboProduceLanguage() {
	}

	public DboProduceLanguage(DboProduce dboProduce,
			DboLanguage dboLanguage) {
		this.produce = dboProduce;
		this.language = dboLanguage;
		this.id = new ProduceLanguageId(produce.getId(),language.getId());
	}
	public DboProduceLanguage(ProduceLanguageId id, DboProduce dboProduce,
			DboLanguage dboLanguage) {
		this.id = id;
		this.produce = dboProduce;
		this.language = dboLanguage;
	}

	public DboProduceLanguage(ProduceLanguageId id, DboProduce dboProduce,
			DboLanguage dboLanguage, String prdLngName) {
		this.id = id;
		this.produce = dboProduce;
		this.language = dboLanguage;
		this.name = prdLngName;
	}

	public ProduceLanguageId getId() {
		return this.id;
	}

	public void setId(ProduceLanguageId id) {
		this.id = id;
	}

	public DboProduce getProduce() {
		return this.produce;
	}

	public void setProduce(DboProduce dboProduce) {
		this.produce = dboProduce;
	}

	public DboLanguage getLanguage() {
		return this.language;
	}

	public void setLanguage(DboLanguage dboLanguage) {
		this.language = dboLanguage;
	}


	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Embeddable
	public static class ProduceLanguageId implements java.io.Serializable {
		@Column(name = "PRD_ID", nullable = false)
		private Integer produceId;

		@Column(name = "LNG_ID", nullable = false)
		private Integer languageId;

		public ProduceLanguageId() {
		}

		public ProduceLanguageId(Integer produceId, Integer languageId) {
			this.produceId = produceId;
			this.languageId = languageId;
		}

		public Integer getProduceId() {
			return produceId;
		}

		public void setProduceId(Integer produceId) {
			this.produceId = produceId;
		}

		public Integer getLanguageId() {
			return languageId;
		}

		public void setLanguageId(Integer languageId) {
			this.languageId = languageId;
		}

		public boolean equals(Object o) {
			if (this == o) return true;
			if (o == null || getClass() != o.getClass()) return false;

			ProduceLanguageId that = (ProduceLanguageId) o;

			if (!languageId.equals(that.languageId)) return false;
			if (!produceId.equals(that.produceId)) return false;

			return true;
		}

		public int hashCode() {
			int result;
			result = produceId.hashCode();
			result = 31 * result + languageId.hashCode();
			return result;
		}
	}

}
