package net.sam.dcl.dbo;

// Generated 23-May-2007 22:53:40 by Hibernate Tools 3.2.0.b9

import net.sam.dcl.beans.ReportDelimiterConsts;
import net.sam.dcl.controller.ActionContext;
import net.sam.dcl.controller.IActionContext;
import net.sam.dcl.util.HibernateUtil;
import net.sam.dcl.util.StringUtil;
import net.sam.dcl.util.StrutsUtil;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import org.hibernate.annotations.Cascade;

import javax.persistence.*;
import java.util.*;

/**
 * DboProduce generated by hbm2java
 */
@Entity
@Table(name = "DCL_PRODUCE")
@SequenceGenerator(name = "GEN_DCL_PRODUCE_ID", sequenceName = "GEN_DCL_PRODUCE_ID", allocationSize = 1)
public class DboProduce implements java.io.Serializable
{
  protected static Log log = LogFactory.getLog(DboProduce.class);

  @Id
  @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "GEN_DCL_PRODUCE_ID")
  @Column(name = "PRD_ID", unique = true, nullable = false)
  private Integer id;

  @ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(name = "UNT_ID")
  private DboUnit unit;

  @Column(name = "CUS_CODE", nullable = true, length = 10)
  private String cusCode;

  @ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(name = "CAT_ID", nullable = false)
  private DboCategory category;

  @Column(name = "PRD_NAME", length = 1000)
  private String name;

  @Column(name = "PRD_TYPE", length = 200)
  private String type;

  @Column(name = "PRD_PARAMS", length = 200)
  private String params;

  @Column(name = "PRD_ADD_PARAMS", length = 200)
  private String addParams;

  @Column(name = "PRD_NOT_CHECK_DOUBLE")
  private String notCheckDouble;

  @OneToMany(fetch = FetchType.LAZY, mappedBy = "produce")
  @Cascade({org.hibernate.annotations.CascadeType.ALL,
          org.hibernate.annotations.CascadeType.DELETE_ORPHAN})
  @org.hibernate.annotations.MapKey(columns = @Column(name = "STF_ID"))
  @OrderBy("stuffCategory")
  private Map<Integer, DboCatalogNumber> catalogNumbers = new LinkedHashMap<Integer, DboCatalogNumber>();

  @OneToMany(fetch = FetchType.LAZY, mappedBy = "produce")
  @Cascade({org.hibernate.annotations.CascadeType.ALL,
          org.hibernate.annotations.CascadeType.DELETE_ORPHAN})
  @MapKey(name = "langCode")
  @OrderBy("language")
  private Map<String, DboProduceLanguage> produceLanguages = new LinkedHashMap<String, DboProduceLanguage>();

  @Column(name = "PRD_BLOCK")
  private Short block;

  @ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(name = "USR_ID_CREATE")
  private DboUser createUser;

  @Column(name = "PRD_CREATE_DATE")
  private Date createDate;

  @ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(name = "USR_ID_EDIT")
  private DboUser editUser;

  @Column(name = "PRD_EDIT_DATE")
  private Date editDate;

  @ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(name = "USR_ID_BLOCK")
  private DboUser blockUser;

  @Column(name = "PRD_BLOCK_DATE")
  private Date blockDate;

  @Column(name = "PRD_MATERIAL")
  private String material;

  @Column(name = "PRD_PURPOSE")
  private String purpose;

  @Column(name = "PRD_SPECIFICATION")
  private String specification;

  @Column(name = "PRD_PRINCIPLE")
  private String principle;

  public DboProduce()
  {
  }

  public DboProduce(Integer prdId, DboCategory dboCategory)
  {
    this.id = prdId;
    this.category = dboCategory;
  }

  public DboProduce(Integer prdId, DboUnit dboUnit, String dboCustomCode,
                    DboCategory dboCategory, String prdName, String prdType,
                    String prdParams, String prdAddParams,
                    Map<Integer, DboCatalogNumber> dboCatalogNumbers,
                    Map<String, DboProduceLanguage> dclProduceLanguages)
  {
    this.id = prdId;
    this.unit = dboUnit;
    this.cusCode = dboCustomCode;
    this.category = dboCategory;
    this.name = prdName;
    this.type = prdType;
    this.params = prdParams;
    this.addParams = prdAddParams;
    this.catalogNumbers = dboCatalogNumbers;
    this.produceLanguages = dclProduceLanguages;
  }

  public DboProduce(Integer prdId, DboUnit dboUnit, String dboCustomCode,
                    DboCategory dboCategory, String prdName, String prdType,
                    String prdParams, String prdAddParams, String prdMaterial,
                    String prdPurpose, String prdSpecification,
                    String prdPrinciple)
  {
    this.id = prdId;
    this.unit = dboUnit;
    this.cusCode = dboCustomCode;
    this.category = dboCategory;
    this.name = prdName;
    this.type = prdType;
    this.params = prdParams;
    this.addParams = prdAddParams;
    this.material = prdMaterial;
    this.purpose = prdPurpose;
    this.specification = prdSpecification;
    this.principle = prdPrinciple;
  }

  public Integer getId()
  {
    return id;
  }

  public void setId(Integer id)
  {
    this.id = id;
  }

  public DboUnit getUnit()
  {
    return this.unit;
  }

  public void setUnit(DboUnit unit)
  {
    this.unit = unit;
  }

  public boolean isCustomCodeEmpty()
  {
    return StringUtil.isEmpty(cusCode);
  }

  public String getCusCode()
  {
    return cusCode;
  }

  public List<DboCustomCode> getCustomCodes()
  {
    return HibernateUtil.getSessionFactory().getCurrentSession()
            .getNamedQuery("produce-custom-codes")
            .setString("code", cusCode)
            .list();
  }

  public DboCustomCode getLastCustomCode()
  {
    return (DboCustomCode) HibernateUtil.getSessionFactory().getCurrentSession()
            .getNamedQuery("produce-last-custom-code")
            .setString("code", cusCode)
            .uniqueResult();
  }

  public DboCustomCode getCustomCodeForDate(Date date, String code)
  {
    return (DboCustomCode) HibernateUtil.getSessionFactory().getCurrentSession()
            .getNamedQuery("produce-custom-code-for-date")
            .setString("code", code)
            .setDate("date", date)
            .uniqueResult();
  }

  public static List<DboProduce> findByCatalogNumberAndStuffCategory(String number, Integer stf_id)
  {
    return (List<DboProduce>) HibernateUtil.getSessionFactory().getCurrentSession()
            .getNamedQuery("produce-by-stuffCategory-and-catalogNumber")
            .setString("number", number)
            .setInteger("stf_id", stf_id)
            .list();
  }

  public static List<DboProduce> findByCatalogNumber(String number)
  {
    return (List<DboProduce>) HibernateUtil.getSessionFactory().getCurrentSession()
            .getNamedQuery("produce-by-catalogNumber")
            .setString("number", number)
            .list();
  }

  public static List<DboProduce> findByCatalogNumberAndStuffCategory(String number, DboStuffCategory stuffCategory)
  {
    return findByCatalogNumberAndStuffCategory(number, stuffCategory.getId());
  }

  public void setCustomCode(DboCustomCode customCode)
  {
    this.cusCode = customCode.getCode();
  }

  public void setCustomCode(String customCode)
  {
    this.cusCode = customCode;
  }

  public DboCategory getCategory()
  {
    return this.category;
  }

  public void setCategory(DboCategory category)
  {
    this.category = category;
  }


  public String getName()
  {
    return this.name;
  }

  public void setName(String name)
  {
    this.name = name;
  }


  public String getType()
  {
    return this.type;
  }

  public void setType(String type)
  {
    this.type = type;
  }


  public String getParams()
  {
    return this.params;
  }

  public void setParams(String params)
  {
    this.params = params;
  }


  public String getAddParams()
  {
    return this.addParams;
  }

  public void setAddParams(String addParams)
  {
    this.addParams = addParams;
  }

  public Map<Integer, DboCatalogNumber> getCatalogNumbers()
  {
    return catalogNumbers;
  }

  public void setCatalogNumbers(Map<Integer, DboCatalogNumber> catalogNumbers)
  {
    this.catalogNumbers = catalogNumbers;
  }

  public Map<String, DboProduceLanguage> getProduceLanguages()
  {
    return this.produceLanguages;
  }

  public void setProduceLanguages(
          Map<String, DboProduceLanguage> produceLanguages)
  {
    this.produceLanguages = produceLanguages;
  }

  public void addProduceLanguage(DboProduceLanguage language)
  {
    produceLanguages.put(language.getLanguage().getCode(), language);
  }

  public void setNameForLanguage(String langCode, String name)
  {
    DboProduceLanguage pLanguage = produceLanguages.get(langCode);
    if (pLanguage == null)
    {
      pLanguage = new DboProduceLanguage(this, DboLanguage.DAO.loadByLangCode(langCode));
      produceLanguages.put(langCode, pLanguage);
    }
    pLanguage.setName(name);
  }

  public void addCatalogNumber(DboCatalogNumber catalogNumber)
  {
    catalogNumber.setProduce(this);
    catalogNumbers.put(catalogNumber.getStuffCategory().getId(), catalogNumber);
  }

  public void deleteCatalogNumber(Integer ctnId)
  {
    for (Iterator iterator = catalogNumbers.entrySet().iterator(); iterator.hasNext(); )
    {
      Map.Entry<String, DboCatalogNumber> entry = (Map.Entry<String, DboCatalogNumber>) iterator.next();
      DboCatalogNumber catalogNumber = entry.getValue();
      if (ctnId.equals(catalogNumber.getId()))
      {
        catalogNumber.setProduce(null);
        iterator.remove();
        return;
      }
    }
  }

  public DboCatalogNumber findCatalogNumber(Integer ctnId)
  {
    for (DboCatalogNumber catalogNumber : catalogNumbers.values())
    {
      if (ctnId.equals(catalogNumber.getId())) return catalogNumber;
    }
    return null;
  }

  public DboCatalogNumber findCatalogNumberByNumber(String ctnNumber)
  {
    for (DboCatalogNumber catalogNumber : catalogNumbers.values())
    {
      if (ctnNumber.equals(catalogNumber.getNumber())) return catalogNumber;
    }
    return null;
  }

  public boolean existCatalogNumber(Integer ctnId)
  {
    return findCatalogNumber(ctnId) != null;
  }

  public boolean isExistWithSameStuffCategory(DboCatalogNumber catalogNumber)
  {
    return getCatalogNumbers().containsKey(catalogNumber.getStuffCategory().getId());
  }

  public boolean isExistWithSameStuffCategoryAnotherMontageAdjustment(DboCatalogNumber catalogNumberIn)
  {
    if (
            null == catalogNumberIn.getMontageAdjustment() ||
                    null == catalogNumberIn.getMontageAdjustment().getId()
            )
    {
      return false;
    }

    for (DboCatalogNumber catalogNumber : catalogNumbers.values())
    {
      if (
              null != catalogNumber.getMontageAdjustment() &&
                      null != catalogNumber.getMontageAdjustment().getId()
              )
      {
        if (
                catalogNumber.getId().equals(catalogNumberIn.getId()) &&
                        catalogNumber.getStuffCategory().getId().equals(catalogNumberIn.getStuffCategory().getId()) &&
                        !catalogNumber.getMontageAdjustment().getId().equals(catalogNumberIn.getMontageAdjustment().getId())
                )
        {
          return true;
        }
      }
    }

    return false;
  }

  public boolean isBBlock()
  {
    return Short.valueOf((short) 1).equals(this.block);
  }

  public Short getBlock()
  {
    return this.block;
  }

  public void setBlock(Short block)
  {
    this.block = block;
  }

  public DboUser getCreateUser()
  {
    return createUser;
  }

  public void setCreateUser(DboUser createUser)
  {
    this.createUser = createUser;
  }

  public DboUser getEditUser()
  {
    return editUser;
  }

  public void setEditUser(DboUser editUser)
  {
    this.editUser = editUser;
  }

  public DboUser getBlockUser()
  {
    return blockUser;
  }

  public void setBlockUser(DboUser blockUser)
  {
    this.blockUser = blockUser;
  }

  public Date getCreateDate()
  {
    return createDate;
  }

  public String getCreateDateFormatted()
  {
    return StringUtil.date2appDateString(createDate);
  }

  public void setCreateDate(Date createDate)
  {
    this.createDate = createDate;
  }

  public Date getEditDate()
  {
    return editDate;
  }

  public String getEditDateFormatted()
  {
    return StringUtil.date2appDateString(editDate);
  }

  public void setEditDate(Date editDate)
  {
    this.editDate = editDate;
  }

  public Date getBlockDate()
  {
    return blockDate;
  }

  public String getBlockDateFormatted()
  {
    return StringUtil.date2appDateString(blockDate);
  }

  public void setBlockDate(Date blockDate)
  {
    this.blockDate = blockDate;
  }

  public String getMaterial()
  {
    return material;
  }

  public void setMaterial(String material)
  {
    this.material = material;
  }

  public String getPurpose()
  {
    return purpose;
  }

  public void setPurpose(String purpose)
  {
    this.purpose = purpose;
  }

  public String getSpecification()
  {
    return specification;
  }

  public void setSpecification(String specification)
  {
    this.specification = specification;
  }

  public String getPrinciple()
  {
    return principle;
  }

  public void setPrinciple(String principle)
  {
    this.principle = principle;
  }

  public String getFullName()
  {
    String produce_full_name = getName();
    if (!StringUtil.isEmpty(getType()))
    {
      produce_full_name += " " + getType();
    }
    if (!StringUtil.isEmpty(getParams()))
    {
      produce_full_name += " " + getParams();
    }
    if (!StringUtil.isEmpty(getAddParams()))
    {
      produce_full_name += " " + getAddParams();
    }
    return produce_full_name;
  }

  public String getNotCheckDouble()
  {
    return notCheckDouble;
  }

  public void setNotCheckDouble(String notCheckDouble)
  {
    this.notCheckDouble = notCheckDouble;
  }

  @Transient
  public String getComment(String createUserName)
  {
    String resStr = "";
    IActionContext context = ActionContext.threadInstance();
    try
    {
      if (!StringUtil.isEmpty(createUserName))
        resStr += StrutsUtil.getMessage(context, "NomenclatureProduce.commentCreate", createUserName);
      if (!StringUtil.isEmpty(createUserName) && !StringUtil.isEmpty(getCusCode()))
        resStr += "\n";
      if (!StringUtil.isEmpty(getCusCode()))
        resStr += StrutsUtil.getMessage(context, "NomenclatureProduce.commentCode", getCusCode());
    }
    catch (Exception e)
    {
      log.error(e);
    }

    return resStr;
  }

  public String getCatalogNumbersAsString()
  {
    if (catalogNumbers != null && !catalogNumbers.isEmpty())
    {
      TreeSet<String> numbers = new TreeSet<String>();
      for (DboCatalogNumber catalogNumber : catalogNumbers.values())
      {
        String number = catalogNumber.getNumber();
        if (!StringUtil.isEmpty(number))
        {
          numbers.add(number);
        }
      }

      if (!numbers.isEmpty())
      {
        String representation = "";
        for (String number : numbers)
        {
          representation = representation + number + ", ";
        }

        return representation.substring(0, representation.length() - 2);
      }
    }

    return "";
  }
}
