package net.sam.dcl.dbo;

// Generated 23-May-2007 22:53:40 by Hibernate Tools 3.2.0.b9

import net.sam.dcl.dbo.DboCatalogNumber;
import net.sam.dcl.dbo.dirty.DclShpListProduce;
import net.sam.dcl.dbo.dirty.DclDlrListProduce;
import net.sam.dcl.dbo.dirty.DclPrcListProduce;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.*;

/**
 * DboStuffCategory generated by hbm2java
 */
@Entity
@Table(name = "DCL_STUFF_CATEGORY")
public class DboStuffCategory implements java.io.Serializable {
	@Id
	@Column(name = "STF_ID", unique = true, nullable = false)
	private Integer id;

	@Column(name = "STF_NAME", length = 150)
	private String name;

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "stuffCategory")
	private Set<DboCatalogNumber> catalogNumbers = new HashSet<DboCatalogNumber>();

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "dclStuffCategory")
	private Set<DclShpListProduce> dclShpListProduces = new HashSet<DclShpListProduce>(0);

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "stuffCategory")
	private Set<DclDlrListProduce> dclDlrListProduces = new HashSet<DclDlrListProduce>(0);

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "stuffCategory")
	private Set<DclPrcListProduce> dclPrcListProduces = new HashSet<DclPrcListProduce>(0);

	public DboStuffCategory() {
	}

	public DboStuffCategory(int stfId) {
		this.id = stfId;
	}

	public DboStuffCategory(Integer stfId, String stfName,
			Set<DclShpListProduce> dclShpListProduces,
			Set<DboCatalogNumber> dboCatalogNumbers,
			Set<DclDlrListProduce> dclDlrListProduces,
			Set<DclPrcListProduce> dclPrcListProduces) {
		this.id = stfId;
		this.name = stfName;
		this.dclShpListProduces = dclShpListProduces;
		this.catalogNumbers = dboCatalogNumbers;
		this.dclDlrListProduces = dclDlrListProduces;
		this.dclPrcListProduces = dclPrcListProduces;
	}

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}



	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}


	public Set<DclShpListProduce> getDclShpListProduces() {
		return this.dclShpListProduces;
	}

	public void setDclShpListProduces(Set<DclShpListProduce> dclShpListProduces) {
		this.dclShpListProduces = dclShpListProduces;
	}


	public Set<DboCatalogNumber> getCatalogNumbers() {
		return this.catalogNumbers;
	}

	public void setCatalogNumbers(Set<DboCatalogNumber> catalogNumbers) {
		this.catalogNumbers = catalogNumbers;
	}

	public Set<DclDlrListProduce> getDclDlrListProduces() {
		return this.dclDlrListProduces;
	}

	public void setDclDlrListProduces(Set<DclDlrListProduce> dclDlrListProduces) {
		this.dclDlrListProduces = dclDlrListProduces;
	}


	public Set<DclPrcListProduce> getDclPrcListProduces() {
		return this.dclPrcListProduces;
	}

	public void setDclPrcListProduces(Set<DclPrcListProduce> dclPrcListProduces) {
		this.dclPrcListProduces = dclPrcListProduces;
	}

}
