package net.sam.dcl.dbo;

import org.hibernate.annotations.Formula;

import javax.persistence.*;

/**
 * DclUnitLanguage generated by hbm2java
 */
@Entity
@Table(name = "DCL_UNIT_LANGUAGE")
public class DboUnitLanguage implements java.io.Serializable
{
  @EmbeddedId
  @AttributeOverrides({
  @AttributeOverride(name = "untId", column = @Column(name = "UNT_ID", nullable = false)),
  @AttributeOverride(name = "lngId", column = @Column(name = "LNG_ID", nullable = false))})
  private DboUnitLanguage.UnitLanguageId id;

  @ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(name = "UNT_ID", nullable = false, insertable = false, updatable = false)
  private DboUnit unit;

  @ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(name = "LNG_ID", nullable = false, insertable = false, updatable = false)
  private DboLanguage language;

  @Column(name = "UNT_NAME", length = 150)
  private String name;

  @Formula("(SELECT DCL_LNG.LNG_LETTER_ID FROM DCL_LANGUAGE DCL_LNG where DCL_LNG.LNG_ID=LNG_ID)")
  private String langCode;

  public DboUnitLanguage()
  {
  }

  public DboUnitLanguage(DboUnit dboUnit,
                         DboLanguage dboLanguage)
  {
    this.unit = dboUnit;
    this.language = dboLanguage;
    this.id = new DboUnitLanguage.UnitLanguageId(unit.getId(), language.getId());
  }

  public DboUnitLanguage(DboUnitLanguage.UnitLanguageId id, DboUnit dboUnit,
                         DboLanguage dboLanguage)
  {
    this.id = id;
    this.unit = dboUnit;
    this.language = dboLanguage;
  }

  public DboUnitLanguage(DboUnitLanguage.UnitLanguageId id, DboUnit dboUnit,
                         DboLanguage dboLanguage, String untLngName)
  {
    this.id = id;
    this.unit = dboUnit;
    this.language = dboLanguage;
    this.name = untLngName;
  }

  public DboUnitLanguage.UnitLanguageId getId()
  {
    return this.id;
  }

  public void setId(DboUnitLanguage.UnitLanguageId id)
  {
    this.id = id;
  }

  public DboUnit getUnit()
  {
    return this.unit;
  }

  public void setUnit(DboUnit dboUnit)
  {
    this.unit = dboUnit;
  }

  public DboLanguage getLanguage()
  {
    return this.language;
  }

  public void setLanguage(DboLanguage dboLanguage)
  {
    this.language = dboLanguage;
  }

  public String getName()
  {
    return this.name;
  }

  public void setName(String name)
  {
    this.name = name;
  }

  @Embeddable
  public static class UnitLanguageId implements java.io.Serializable
  {
    @Column(name = "UNT_ID", nullable = false)
    private Integer unitId;

    @Column(name = "LNG_ID", nullable = false)
    private Integer languageId;

    public UnitLanguageId()
    {
    }

    public UnitLanguageId(Integer unitId, Integer languageId)
    {
      this.unitId = unitId;
      this.languageId = languageId;
    }

    public Integer getUnitId()
    {
      return unitId;
    }

    public void setUnitId(Integer unitId)
    {
      this.unitId = unitId;
    }

    public Integer getLanguageId()
    {
      return languageId;
    }

    public void setLanguageId(Integer languageId)
    {
      this.languageId = languageId;
    }

    public boolean equals(Object o)
    {
      if (this == o) return true;
      if (o == null || getClass() != o.getClass()) return false;

      DboUnitLanguage.UnitLanguageId that = (DboUnitLanguage.UnitLanguageId) o;

      if (!languageId.equals(that.languageId)) return false;
      if (!unitId.equals(that.unitId)) return false;

      return true;
    }

    public int hashCode()
    {
      int result;
      result = unitId.hashCode();
      result = 31 * result + languageId.hashCode();
      return result;
    }
  }

}
