package net.sam.dcl.dbo;

// Generated 23-May-2007 22:53:40 by Hibernate Tools 3.2.0.b9

import net.sam.dcl.dbo.dirty.DclDepartment;
import net.sam.dcl.dbo.dirty.DclRole;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.*;

import org.hibernate.annotations.Formula;

/**
 * DclUser generated by hbm2java
 */
@Entity
@Table(name = "DCL_USER")
public class DboUser implements java.io.Serializable
{
  private int usrId;
  private DclDepartment department;
  private String code;
  private String login;
  private String passwd;
  private String phone;
  private Short block;
  private Short responsePerson;
  private Short noLogin;
  private Short chiefDep;
  private String fax;
  private String email;

  private String name;
  private String surname;
  private String position;


  private Set<DboUserLanguage> userLanguages = new HashSet<DboUserLanguage>(0);
  private Set<DclRole> roles = new HashSet<DclRole>(0);

  public DboUser()
  {
  }

  public DboUser(int usrId)
  {
    this.usrId = usrId;
  }

  public DboUser(int usrId, DclDepartment department, String code,
                 String login, String passwd, String phone, Short block,
                 Short responsePerson, Short noLogin, Short chiefDep,
                 String fax, String email,
                 Set<DboUserLanguage> userLanguages,
                 Set<DclRole> dclRoles
  )
  {
    this.usrId = usrId;
    this.department = department;
    this.code = code;
    this.login = login;
    this.passwd = passwd;
    this.phone = phone;
    this.block = block;
    this.responsePerson = responsePerson;
    this.noLogin = noLogin;
    this.chiefDep = chiefDep;
    this.fax = fax;
    this.email = email;
    this.userLanguages = userLanguages;
    this.roles = dclRoles;
  }

  @Id
  @Column(name = "USR_ID", unique = true, nullable = false)
  public int getUsrId()
  {
    return this.usrId;
  }

  public void setUsrId(int usrId)
  {
    this.usrId = usrId;
  }

  @ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(name = "DEP_ID")
  public DclDepartment getDepartment()
  {
    return this.department;
  }

  public void setDepartment(DclDepartment department)
  {
    this.department = department;
  }

  @Column(name = "USR_CODE", length = 3)
  public String getCode()
  {
    return this.code;
  }

  public void setCode(String code)
  {
    this.code = code;
  }

  @Column(name = "USR_LOGIN", length = 8)
  public String getLogin()
  {
    return this.login;
  }

  public void setLogin(String login)
  {
    this.login = login;
  }

  @Column(name = "USR_PASSWD", length = 64)
  public String getPasswd()
  {
    return this.passwd;
  }

  public void setPasswd(String passwd)
  {
    this.passwd = passwd;
  }

  @Column(name = "USR_PHONE", length = 50)
  public String getPhone()
  {
    return this.phone;
  }

  public void setPhone(String phone)
  {
    this.phone = phone;
  }

  @Column(name = "USR_BLOCK")
  public Short getBlock()
  {
    return this.block;
  }

  public void setBlock(Short block)
  {
    this.block = block;
  }

  @Column(name = "USR_RESPONS_PERSON")
  public Short getResponsePerson()
  {
    return this.responsePerson;
  }

  public void setResponsePerson(Short responsePerson)
  {
    this.responsePerson = responsePerson;
  }

  @Column(name = "USR_NO_LOGIN")
  public Short getNoLogin()
  {
    return this.noLogin;
  }

  public void setNoLogin(Short noLogin)
  {
    this.noLogin = noLogin;
  }

  @Column(name = "USR_CHIEF_DEP")
  public Short getChiefDep()
  {
    return this.chiefDep;
  }

  public void setChiefDep(Short chiefDep)
  {
    this.chiefDep = chiefDep;
  }

  @Column(name = "USR_FAX", length = 50)
  public String getFax()
  {
    return this.fax;
  }

  public void setFax(String fax)
  {
    this.fax = fax;
  }

  @Column(name = "USR_EMAIL", length = 100)
  public String getEmail()
  {
    return this.email;
  }

  public void setEmail(String email)
  {
    this.email = email;
  }

  @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "user")
  public Set<DboUserLanguage> getUserLanguages()
  {
    return this.userLanguages;
  }

  public void setUserLanguages(Set<DboUserLanguage> userLanguages)
  {
    this.userLanguages = userLanguages;
  }

  @ManyToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY)
  public Set<DclRole> getRoles()
  {
    return this.roles;
  }

  public void setRoles(Set<DclRole> roles)
  {
    this.roles = roles;
  }

  /*
   *       (select usr_name from dcl_user_language where usr_id = u.usr_id and lng_id = 1) as usr_name,
       (select usr_surname from dcl_user_language where usr_id = u.usr_id and lng_id = 1) as usr_surname,
       (select usr_position from dcl_user_language where usr_id = u.usr_id and lng_id = 1) as usr_position,

   * */
  @Formula("(select ul.usr_name from dcl_user_language ul where ul.usr_id = usr_id and ul.lng_id = 1)")
  public String getName()
  {
    return name;
  }

  public void setName(String name)
  {
    this.name = name;
  }

  @Formula("(select ul.usr_surname from dcl_user_language ul where ul.usr_id = usr_id and ul.lng_id = 1)")
  public String getSurname()
  {
    return surname;
  }

  public void setSurname(String surname)
  {
    this.surname = surname;
  }

  @Formula("(select ul.usr_position from dcl_user_language ul where ul.usr_id = usr_id and ul.lng_id = 1)")
  public String getPosition()
  {
    return position;
  }

  public void setPosition(String position)
  {
    this.position = position;
  }

  @Transient
  public String getUserFullName()
  {
    if (null == name && null == surname)
      return "";

    String retStr = "";
    if (null != surname)
      retStr += surname;
    retStr += " ";
    if (null != name)
      retStr += name;
    return retStr;
  }
}
