package net.sam.dcl.dbo;

// Generated 23-May-2007 22:53:40 by Hibernate Tools 3.2.0.b9

import org.hibernate.annotations.Formula;
import org.hibernate.annotations.Cascade;

import java.util.HashSet;
import java.util.Set;
import java.util.Map;
import java.util.LinkedHashMap;
import javax.persistence.*;

/**
 * DboUnit generated by hbm2java
 */
@Entity
@Table(name = "DCL_UNIT")
@SequenceGenerator(name = "GEN_DCL_UNIT_ID", sequenceName = "GEN_DCL_UNIT_ID", allocationSize = 1)
public class DboUnit implements java.io.Serializable
{
  @Id
  @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "GEN_DCL_UNIT_ID")
  @Column(name = "UNT_ID", unique = true, nullable = false)
  private Integer id;

  @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "unit")
  private Set<DboProduce> produces = new HashSet<DboProduce>();

  @Formula("(select ul.unt_name from dcl_unit_language ul where ul.unt_id = unt_id and ul.lng_id = 1)")
  private String name;

  @OneToMany(fetch = FetchType.LAZY, mappedBy = "unit")
  @Cascade({org.hibernate.annotations.CascadeType.ALL,
          org.hibernate.annotations.CascadeType.DELETE_ORPHAN})
  @MapKey(name = "langCode")
  @OrderBy("language")
  private Map<String, DboUnitLanguage> unitLanguages = new LinkedHashMap<String, DboUnitLanguage>();

	@Column(name = "is_acceptable_for_cpr")
	private boolean isAcceptableForContract;

  public DboUnit()
  {
  }

  public DboUnit(int untId)
  {
    this.id = untId;
  }

  public DboUnit(Integer untId, Set<DboProduce> dboProduces,
                 Map<String, DboUnitLanguage> dclUnitLanguages)
  {
    this.id = untId;
    this.produces = dboProduces;
    this.unitLanguages = dclUnitLanguages;
  }

  public DboUnit(DboUnit unit)
  {
    this.id = unit.getId();
    this.name = unit.getName();
  }

  public Integer getId()
  {
    return id;
  }

  public void setId(Integer id)
  {
    this.id = id;
  }


  public String getName()
  {
    return name;
  }

  public void setName(String name)
  {
    this.name = name;
  }

  public Set<DboProduce> getProduces()
  {
    return this.produces;
  }

  public void setProduces(Set<DboProduce> produces)
  {
    this.produces = produces;
  }

  public Map<String, DboUnitLanguage> getUnitLanguages()
  {
    return this.unitLanguages;
  }

  public void setUnitLanguages(Map<String, DboUnitLanguage> unitLanguages)
  {
    this.unitLanguages = unitLanguages;
  }

  public void addUnitLanguage(DboUnitLanguage language)
  {
    unitLanguages.put(language.getLanguage().getCode(), language);
  }

  public void setNameForLanguage(String langCode, String name)
  {
    DboUnitLanguage pLanguage = unitLanguages.get(langCode);
    if (pLanguage == null)
    {
      pLanguage = new DboUnitLanguage(this, DboLanguage.DAO.loadByLangCode(langCode));
      unitLanguages.put(langCode, pLanguage);
    }
    pLanguage.setName(name);
  }

	public boolean isAcceptableForContract() {
		return isAcceptableForContract;
	}

	public void setAcceptableForContract(boolean isAcceptableForContract) {
		this.isAcceptableForContract = isAcceptableForContract;
	}
}
