package net.sam.dcl.dbo;

// Generated 23-May-2007 22:53:40 by Hibernate Tools 3.2.0.b9

import net.sam.dcl.dbo.DboLanguage;
import net.sam.dcl.dbo.DboUser;
import net.sam.dcl.dbo.dirty.DclUserLanguageId;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * DclUserLanguage generated by hbm2java
 */
@Entity
@Table(name = "DCL_USER_LANGUAGE")
public class DboUserLanguage implements java.io.Serializable {

	private DclUserLanguageId id;

	private DboUser user;

	private DboLanguage language;

	private String surname;

	private String name;

	private String position;

	public DboUserLanguage() {
	}

	public DboUserLanguage(DclUserLanguageId id, DboUser user,
			DboLanguage dboLanguage) {
		this.id = id;
		this.user = user;
		this.language = dboLanguage;
	}

	public DboUserLanguage(DclUserLanguageId id, DboUser user,
			DboLanguage dboLanguage, String surname, String name,
			String position) {
		this.id = id;
		this.user = user;
		this.language = dboLanguage;
		this.surname = surname;
		this.name = name;
		this.position = position;
	}

	@EmbeddedId
	@AttributeOverrides( {
			@AttributeOverride(name = "usrId", column = @Column(name = "USR_ID", nullable = false)),
			@AttributeOverride(name = "lngId", column = @Column(name = "LNG_ID", nullable = false)) })
	public DclUserLanguageId getId() {
		return this.id;
	}

	public void setId(DclUserLanguageId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "USR_ID", nullable = false, insertable = false, updatable = false)
	public DboUser getUser() {
		return this.user;
	}

	public void setUser(DboUser user) {
		this.user = user;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "LNG_ID", nullable = false, insertable = false, updatable = false)
	public DboLanguage getLanguage() {
		return this.language;
	}

	public void setLanguage(DboLanguage dboLanguage) {
		this.language = dboLanguage;
	}

	@Column(name = "USR_SURNAME", length = 20)
	public String getSurname() {
		return this.surname;
	}

	public void setSurname(String surname) {
		this.surname = surname;
	}

	@Column(name = "USR_NAME", length = 20)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "USR_POSITION", length = 60)
	public String getPosition() {
		return this.position;
	}

	public void setPosition(String position) {
		this.position = position;
	}

}
