package net.sam.dcl.dbo.dirty;

// Generated 23-May-2007 22:53:40 by Hibernate Tools 3.2.0.b9

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DclCustomCodeVId generated by hbm2java
 */
@Embeddable
public class DclCustomCodeVId implements java.io.Serializable {

	private String cusCode;

	private Date cusInstant;

	public DclCustomCodeVId() {
	}

	public DclCustomCodeVId(String cusCode, Date cusInstant) {
		this.cusCode = cusCode;
		this.cusInstant = cusInstant;
	}

	@Column(name = "CUS_CODE", length = 0)
	public String getCusCode() {
		return this.cusCode;
	}

	public void setCusCode(String cusCode) {
		this.cusCode = cusCode;
	}

	@Column(name = "CUS_INSTANT", length = 19)
	public Date getCusInstant() {
		return this.cusInstant;
	}

	public void setCusInstant(Date cusInstant) {
		this.cusInstant = cusInstant;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DclCustomCodeVId))
			return false;
		DclCustomCodeVId castOther = (DclCustomCodeVId) other;

		return ((this.getCusCode() == castOther.getCusCode()) || (this
				.getCusCode() != null
				&& castOther.getCusCode() != null && this.getCusCode().equals(
				castOther.getCusCode())))
				&& ((this.getCusInstant() == castOther.getCusInstant()) || (this
						.getCusInstant() != null
						&& castOther.getCusInstant() != null && this
						.getCusInstant().equals(castOther.getCusInstant())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getCusCode() == null ? 0 : this.getCusCode().hashCode());
		result = 37
				* result
				+ (getCusInstant() == null ? 0 : this.getCusInstant()
						.hashCode());
		return result;
	}

}
