package net.sam.dcl.dbo.dirty;

// Generated 23-May-2007 22:53:40 by Hibernate Tools 3.2.0.b9

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * DclCustomCodeV generated by hbm2java
 */
@Entity
@Table(name = "DCL_CUSTOM_CODE_V")
public class DclCustomCodeV implements java.io.Serializable {

	private DclCustomCodeVId id;

	public DclCustomCodeV() {
	}

	public DclCustomCodeV(DclCustomCodeVId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides( {
			@AttributeOverride(name = "cusCode", column = @Column(name = "CUS_CODE", length = 0)),
			@AttributeOverride(name = "cusInstant", column = @Column(name = "CUS_INSTANT", length = 19)) })
	public DclCustomCodeVId getId() {
		return this.id;
	}

	public void setId(DclCustomCodeVId id) {
		this.id = id;
	}

}
