package net.sam.dcl.dbo.dirty;

// Generated 23-May-2007 22:53:40 by Hibernate Tools 3.2.0.b9

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DclConListSpec generated by hbm2java
 */
@Entity
@Table(name = "DCL_CON_LIST_SPEC")
public class DclConListSpec implements java.io.Serializable {

	private int spcId;

	private DclContract dclContract;

	private String spcNumber;

	private Date spcDate;

	private BigDecimal spcSumm;

	private BigDecimal spcSummNds;

	private Short spcExecuted;

	private BigDecimal spcNdsRate;

	private Date spcDeliveryDate;

	private Short spcPayCondFlag;

	private String spcAddPayCond;

	private Short spcOriginal;

	private Set<DclPayListSum> dclPayListSums = new HashSet<DclPayListSum>(0);

	private Set<DclShipping> dclShippings = new HashSet<DclShipping>(0);

	private Set<DclCtcList> dclCtcLists = new HashSet<DclCtcList>(0);

	public DclConListSpec() {
	}

	public DclConListSpec(int spcId, Date spcDeliveryDate) {
		this.spcId = spcId;
		this.spcDeliveryDate = spcDeliveryDate;
	}

	public DclConListSpec(int spcId, DclContract dclContract, String spcNumber,
			Date spcDate, BigDecimal spcSumm, BigDecimal spcSummNds,
			Short spcExecuted, BigDecimal spcNdsRate, Date spcDeliveryDate,
			Short spcPayCondFlag, String spcAddPayCond, Short spcOriginal,
			Set<DclPayListSum> dclPayListSums,
			Set<DclShipping> dclShippings, Set<DclCtcList> dclCtcLists) {
		this.spcId = spcId;
		this.dclContract = dclContract;
		this.spcNumber = spcNumber;
		this.spcDate = spcDate;
		this.spcSumm = spcSumm;
		this.spcSummNds = spcSummNds;
		this.spcExecuted = spcExecuted;
		this.spcNdsRate = spcNdsRate;
		this.spcDeliveryDate = spcDeliveryDate;
		this.spcPayCondFlag = spcPayCondFlag;
		this.spcAddPayCond = spcAddPayCond;
		this.spcOriginal = spcOriginal;
		this.dclPayListSums = dclPayListSums;
		this.dclShippings = dclShippings;
		this.dclCtcLists = dclCtcLists;
	}

	@Id
	@Column(name = "SPC_ID", unique = true, nullable = false)
	public int getSpcId() {
		return this.spcId;
	}

	public void setSpcId(int spcId) {
		this.spcId = spcId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CON_ID")
	public DclContract getDclContract() {
		return this.dclContract;
	}

	public void setDclContract(DclContract dclContract) {
		this.dclContract = dclContract;
	}

	@Column(name = "SPC_NUMBER", length = 50)
	public String getSpcNumber() {
		return this.spcNumber;
	}

	public void setSpcNumber(String spcNumber) {
		this.spcNumber = spcNumber;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "SPC_DATE", length = 10)
	public Date getSpcDate() {
		return this.spcDate;
	}

	public void setSpcDate(Date spcDate) {
		this.spcDate = spcDate;
	}

	@Column(name = "SPC_SUMM", precision = 15)
	public BigDecimal getSpcSumm() {
		return this.spcSumm;
	}

	public void setSpcSumm(BigDecimal spcSumm) {
		this.spcSumm = spcSumm;
	}

	@Column(name = "SPC_SUMM_NDS", precision = 15)
	public BigDecimal getSpcSummNds() {
		return this.spcSummNds;
	}

	public void setSpcSummNds(BigDecimal spcSummNds) {
		this.spcSummNds = spcSummNds;
	}

	@Column(name = "SPC_EXECUTED")
	public Short getSpcExecuted() {
		return this.spcExecuted;
	}

	public void setSpcExecuted(Short spcExecuted) {
		this.spcExecuted = spcExecuted;
	}

	@Column(name = "SPC_NDS_RATE", precision = 15)
	public BigDecimal getSpcNdsRate() {
		return this.spcNdsRate;
	}

	public void setSpcNdsRate(BigDecimal spcNdsRate) {
		this.spcNdsRate = spcNdsRate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "SPC_DELIVERY_DATE", nullable = false, length = 10)
	public Date getSpcDeliveryDate() {
		return this.spcDeliveryDate;
	}

	public void setSpcDeliveryDate(Date spcDeliveryDate) {
		this.spcDeliveryDate = spcDeliveryDate;
	}

	public void setSpcPayCondFlag(Short spcPayCondFlag) {
		this.spcPayCondFlag = spcPayCondFlag;
	}

	@Column(name = "SPC_ADD_PAY_COND", length = 5000)
	public String getSpcAddPayCond() {
		return this.spcAddPayCond;
	}

	public void setSpcAddPayCond(String spcAddPayCond) {
		this.spcAddPayCond = spcAddPayCond;
	}

	@Column(name = "SPC_ORIGINAL")
	public Short getSpcOriginal() {
		return this.spcOriginal;
	}

	public void setSpcOriginal(Short spcOriginal) {
		this.spcOriginal = spcOriginal;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "dclConListSpec")
	public Set<DclPayListSum> getDclPayListSums() {
		return this.dclPayListSums;
	}

	public void setDclPayListSums(Set<DclPayListSum> dclPayListSums) {
		this.dclPayListSums = dclPayListSums;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "dclConListSpec")
	public Set<DclShipping> getDclShippings() {
		return this.dclShippings;
	}

	public void setDclShippings(Set<DclShipping> dclShippings) {
		this.dclShippings = dclShippings;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "dclConListSpec")
	public Set<DclCtcList> getDclCtcLists() {
		return this.dclCtcLists;
	}

	public void setDclCtcLists(Set<DclCtcList> dclCtcLists) {
		this.dclCtcLists = dclCtcLists;
	}

}
