package net.sam.dcl.dbo.dirty;

// Generated 23-May-2007 22:53:40 by Hibernate Tools 3.2.0.b9

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * DclCtcList generated by hbm2java
 */
@Entity
@Table(name = "DCL_CTC_LIST")
public class DclCtcList implements java.io.Serializable {

	private int lccId;

	private DclContractClosed dclContractClosed;

	private DclConListSpec dclConListSpec;

	private BigDecimal lccCharges;

	public DclCtcList() {
	}

	public DclCtcList(int lccId) {
		this.lccId = lccId;
	}

	public DclCtcList(int lccId, DclContractClosed dclContractClosed,
			DclConListSpec dclConListSpec, BigDecimal lccCharges) {
		this.lccId = lccId;
		this.dclContractClosed = dclContractClosed;
		this.dclConListSpec = dclConListSpec;
		this.lccCharges = lccCharges;
	}

	@Id
	@Column(name = "LCC_ID", unique = true, nullable = false)
	public int getLccId() {
		return this.lccId;
	}

	public void setLccId(int lccId) {
		this.lccId = lccId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CTC_ID")
	public DclContractClosed getDclContractClosed() {
		return this.dclContractClosed;
	}

	public void setDclContractClosed(DclContractClosed dclContractClosed) {
		this.dclContractClosed = dclContractClosed;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SPC_ID")
	public DclConListSpec getDclConListSpec() {
		return this.dclConListSpec;
	}

	public void setDclConListSpec(DclConListSpec dclConListSpec) {
		this.dclConListSpec = dclConListSpec;
	}

	@Column(name = "LCC_CHARGES", precision = 15)
	public BigDecimal getLccCharges() {
		return this.lccCharges;
	}

	public void setLccCharges(BigDecimal lccCharges) {
		this.lccCharges = lccCharges;
	}

}
