package net.sam.dcl.dbo.dirty;

// Generated 23-May-2007 22:53:40 by Hibernate Tools 3.2.0.b9

import net.sam.dcl.dbo.DboUser;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DclContractClosed generated by hbm2java
 */
@Entity
@Table(name = "DCL_CONTRACT_CLOSED")
public class DclContractClosed implements java.io.Serializable {

	private int ctcId;

	private DboUser dclUserByUsrIdCreate;

	private DboUser dclUserByUsrIdEdit;

	private Date ctcCreateDate;

	private Date ctcEditDate;

	private int ctcNumber;

	private Date ctcDate;

	private Short ctcBlock;

	private Set<DclCtcList> dclCtcLists = new HashSet<DclCtcList>(0);

	public DclContractClosed() {
	}

	public DclContractClosed(int ctcId, int ctcNumber) {
		this.ctcId = ctcId;
		this.ctcNumber = ctcNumber;
	}

	public DclContractClosed(int ctcId, DboUser dclUserByUsrIdCreate,
			DboUser dclUserByUsrIdEdit, Date ctcCreateDate, Date ctcEditDate,
			int ctcNumber, Date ctcDate, Short ctcBlock,
			Set<DclCtcList> dclCtcLists) {
		this.ctcId = ctcId;
		this.dclUserByUsrIdCreate = dclUserByUsrIdCreate;
		this.dclUserByUsrIdEdit = dclUserByUsrIdEdit;
		this.ctcCreateDate = ctcCreateDate;
		this.ctcEditDate = ctcEditDate;
		this.ctcNumber = ctcNumber;
		this.ctcDate = ctcDate;
		this.ctcBlock = ctcBlock;
		this.dclCtcLists = dclCtcLists;
	}

	@Id
	@Column(name = "CTC_ID", unique = true, nullable = false)
	public int getCtcId() {
		return this.ctcId;
	}

	public void setCtcId(int ctcId) {
		this.ctcId = ctcId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "USR_ID_CREATE")
	public DboUser getDclUserByUsrIdCreate() {
		return this.dclUserByUsrIdCreate;
	}

	public void setDclUserByUsrIdCreate(DboUser dclUserByUsrIdCreate) {
		this.dclUserByUsrIdCreate = dclUserByUsrIdCreate;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "USR_ID_EDIT")
	public DboUser getDclUserByUsrIdEdit() {
		return this.dclUserByUsrIdEdit;
	}

	public void setDclUserByUsrIdEdit(DboUser dclUserByUsrIdEdit) {
		this.dclUserByUsrIdEdit = dclUserByUsrIdEdit;
	}

	@Column(name = "CTC_CREATE_DATE", length = 19)
	public Date getCtcCreateDate() {
		return this.ctcCreateDate;
	}

	public void setCtcCreateDate(Date ctcCreateDate) {
		this.ctcCreateDate = ctcCreateDate;
	}

	@Column(name = "CTC_EDIT_DATE", length = 19)
	public Date getCtcEditDate() {
		return this.ctcEditDate;
	}

	public void setCtcEditDate(Date ctcEditDate) {
		this.ctcEditDate = ctcEditDate;
	}

	@Column(name = "CTC_NUMBER", nullable = false)
	public int getCtcNumber() {
		return this.ctcNumber;
	}

	public void setCtcNumber(int ctcNumber) {
		this.ctcNumber = ctcNumber;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CTC_DATE", length = 10)
	public Date getCtcDate() {
		return this.ctcDate;
	}

	public void setCtcDate(Date ctcDate) {
		this.ctcDate = ctcDate;
	}

	@Column(name = "CTC_BLOCK")
	public Short getCtcBlock() {
		return this.ctcBlock;
	}

	public void setCtcBlock(Short ctcBlock) {
		this.ctcBlock = ctcBlock;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "dclContractClosed")
	public Set<DclCtcList> getDclCtcLists() {
		return this.dclCtcLists;
	}

	public void setDclCtcLists(Set<DclCtcList> dclCtcLists) {
		this.dclCtcLists = dclCtcLists;
	}

}
