package net.sam.dcl.dbo.dirty;

// Generated 23-May-2007 22:53:40 by Hibernate Tools 3.2.0.b9

import net.sam.dcl.dbo.DboUser;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * DclContractor generated by hbm2java
 */
@Entity
@Table(name = "DCL_CONTRACTOR", uniqueConstraints = @UniqueConstraint(columnNames = "CTR_UNP"))
public class DclContractor implements java.io.Serializable {

	private int ctrId;

	private DboUser dclUserByUsrIdCreate;

	private DboUser dclUserByUsrIdEdit;

	private String ctrName;

	private String ctrAddress;

	private String ctrEmail;

	private String ctrBankProps;

	private String ctrAccount1;

	private String ctrAccount2;

	private String ctrUnp;

	private String ctrFullName;

	private Short ctrBlock;

	private Date ctrCreateDate;

	private Date ctrEditDate;

	private Set<DclCommercialProposal> dclCommercialProposals = new HashSet<DclCommercialProposal>(
			0);

	private Set<DclShipping> dclShippings = new HashSet<DclShipping>(0);

	private Set<DclContract> dclContracts = new HashSet<DclContract>(0);

	private Set<DclContactPerson> dclContactPersons = new HashSet<DclContactPerson>(
			0);

	private Set<DclDlrListProduce> dclDlrListProduces = new HashSet<DclDlrListProduce>(
			0);

	private Set<DclPayment> dclPayments = new HashSet<DclPayment>(0);

	public DclContractor() {
	}

	public DclContractor(int ctrId, String ctrName) {
		this.ctrId = ctrId;
		this.ctrName = ctrName;
	}

	public DclContractor(int ctrId, DboUser dclUserByUsrIdCreate,
			DboUser dclUserByUsrIdEdit, String ctrName, String ctrAddress,
			String ctrEmail, String ctrBankProps, String ctrAccount1,
			String ctrAccount2, String ctrUnp, String ctrFullName,
			Short ctrBlock, Date ctrCreateDate, Date ctrEditDate,
			Set<DclCommercialProposal> dclCommercialProposals,
			Set<DclShipping> dclShippings,
			Set<DclContract> dclContracts,
			Set<DclContactPerson> dclContactPersons,
			Set<DclDlrListProduce> dclDlrListProduces,
			Set<DclPayment> dclPayments) {
		this.ctrId = ctrId;
		this.dclUserByUsrIdCreate = dclUserByUsrIdCreate;
		this.dclUserByUsrIdEdit = dclUserByUsrIdEdit;
		this.ctrName = ctrName;
		this.ctrAddress = ctrAddress;
		this.ctrEmail = ctrEmail;
		this.ctrBankProps = ctrBankProps;
		this.ctrAccount1 = ctrAccount1;
		this.ctrAccount2 = ctrAccount2;
		this.ctrUnp = ctrUnp;
		this.ctrFullName = ctrFullName;
		this.ctrBlock = ctrBlock;
		this.ctrCreateDate = ctrCreateDate;
		this.ctrEditDate = ctrEditDate;
		this.dclCommercialProposals = dclCommercialProposals;
		this.dclShippings = dclShippings;
		this.dclContracts = dclContracts;
		this.dclContactPersons = dclContactPersons;
		this.dclDlrListProduces = dclDlrListProduces;
		this.dclPayments = dclPayments;
	}

	@Id
	@Column(name = "CTR_ID", unique = true, nullable = false)
	public int getCtrId() {
		return this.ctrId;
	}

	public void setCtrId(int ctrId) {
		this.ctrId = ctrId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "USR_ID_CREATE")
	public DboUser getDclUserByUsrIdCreate() {
		return this.dclUserByUsrIdCreate;
	}

	public void setDclUserByUsrIdCreate(DboUser dclUserByUsrIdCreate) {
		this.dclUserByUsrIdCreate = dclUserByUsrIdCreate;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "USR_ID_EDIT")
	public DboUser getDclUserByUsrIdEdit() {
		return this.dclUserByUsrIdEdit;
	}

	public void setDclUserByUsrIdEdit(DboUser dclUserByUsrIdEdit) {
		this.dclUserByUsrIdEdit = dclUserByUsrIdEdit;
	}

	@Column(name = "CTR_NAME", nullable = false, length = 200)
	public String getCtrName() {
		return this.ctrName;
	}

	public void setCtrName(String ctrName) {
		this.ctrName = ctrName;
	}

	@Column(name = "CTR_ADDRESS", length = 100)
	public String getCtrAddress() {
		return this.ctrAddress;
	}

	public void setCtrAddress(String ctrAddress) {
		this.ctrAddress = ctrAddress;
	}

	@Column(name = "CTR_EMAIL", length = 40)
	public String getCtrEmail() {
		return this.ctrEmail;
	}

	public void setCtrEmail(String ctrEmail) {
		this.ctrEmail = ctrEmail;
	}

	@Column(name = "CTR_BANK_PROPS", length = 300)
	public String getCtrBankProps() {
		return this.ctrBankProps;
	}

	public void setCtrBankProps(String ctrBankProps) {
		this.ctrBankProps = ctrBankProps;
	}

	@Column(name = "CTR_ACCOUNT1", length = 35)
	public String getCtrAccount1() {
		return this.ctrAccount1;
	}

	public void setCtrAccount1(String ctrAccount1) {
		this.ctrAccount1 = ctrAccount1;
	}

	@Column(name = "CTR_ACCOUNT2", length = 35)
	public String getCtrAccount2() {
		return this.ctrAccount2;
	}

	public void setCtrAccount2(String ctrAccount2) {
		this.ctrAccount2 = ctrAccount2;
	}

	@Column(name = "CTR_UNP", unique = true, length = 15)
	public String getCtrUnp() {
		return this.ctrUnp;
	}

	public void setCtrUnp(String ctrUnp) {
		this.ctrUnp = ctrUnp;
	}

	@Column(name = "CTR_FULL_NAME", length = 300)
	public String getCtrFullName() {
		return this.ctrFullName;
	}

	public void setCtrFullName(String ctrFullName) {
		this.ctrFullName = ctrFullName;
	}

	@Column(name = "CTR_BLOCK")
	public Short getCtrBlock() {
		return this.ctrBlock;
	}

	public void setCtrBlock(Short ctrBlock) {
		this.ctrBlock = ctrBlock;
	}

	@Column(name = "CTR_CREATE_DATE", length = 19)
	public Date getCtrCreateDate() {
		return this.ctrCreateDate;
	}

	public void setCtrCreateDate(Date ctrCreateDate) {
		this.ctrCreateDate = ctrCreateDate;
	}

	@Column(name = "CTR_EDIT_DATE", length = 19)
	public Date getCtrEditDate() {
		return this.ctrEditDate;
	}

	public void setCtrEditDate(Date ctrEditDate) {
		this.ctrEditDate = ctrEditDate;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "dclContractor")
	public Set<DclCommercialProposal> getDclCommercialProposals() {
		return this.dclCommercialProposals;
	}

	public void setDclCommercialProposals(
			Set<DclCommercialProposal> dclCommercialProposals) {
		this.dclCommercialProposals = dclCommercialProposals;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "dclContractor")
	public Set<DclShipping> getDclShippings() {
		return this.dclShippings;
	}

	public void setDclShippings(Set<DclShipping> dclShippings) {
		this.dclShippings = dclShippings;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "dclContractor")
	public Set<DclContract> getDclContracts() {
		return this.dclContracts;
	}

	public void setDclContracts(Set<DclContract> dclContracts) {
		this.dclContracts = dclContracts;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "dclContractor")
	public Set<DclContactPerson> getDclContactPersons() {
		return this.dclContactPersons;
	}

	public void setDclContactPersons(Set<DclContactPerson> dclContactPersons) {
		this.dclContactPersons = dclContactPersons;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "dclContractor")
	public Set<DclDlrListProduce> getDclDlrListProduces() {
		return this.dclDlrListProduces;
	}

	public void setDclDlrListProduces(Set<DclDlrListProduce> dclDlrListProduces) {
		this.dclDlrListProduces = dclDlrListProduces;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "dclContractor")
	public Set<DclPayment> getDclPayments() {
		return this.dclPayments;
	}

	public void setDclPayments(Set<DclPayment> dclPayments) {
		this.dclPayments = dclPayments;
	}

}
