package net.sam.dcl.dbo.dirty;

// Generated 23-May-2007 22:53:40 by Hibernate Tools 3.2.0.b9

import net.sam.dcl.dbo.DboUser;
import net.sam.dcl.dbo.DboCprListProduce;

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DclCommercialProposal generated by hbm2java
 */
@Entity
@Table(name = "DCL_COMMERCIAL_PROPOSAL")
public class DclCommercialProposal implements java.io.Serializable {

	private int cprId;

	private DboUser dclUserByUsrId;

	private DclCurrency dclCurrency;

	private DclContractor dclContractor;

	private DboUser dclUserByUsrIdCreate;

	private DclContactPerson dclContactPerson;

	private DboUser dclUserByUsrIdEdit;

	private DclTermInco dclTermIncoByTrmIdDeliveryCondition;

	private DclTermInco dclTermIncoByTrmIdPriceCondition;

	private Date cprCreateDate;

	private Date cprEditDate;

	private String cprNumber;

	private Date cprDate;

	private String cprConcerning;

	private String cprPreamble;

	private BigDecimal cprCourse;

	private BigDecimal cprNds;

	private String cprCountry;

	private String cprPayCondition;

	private String cprDeliveryAddress;

	private BigDecimal cprSumTransport;

	private String cprDeliveryTerm;

	private String cprAddInfo;

	private Date cprFinalDate;

	private Short cprProposalReceivedFlag;

	private Date cprDateAccept;

	private Short cprBlock;

	private String cprImgName;

	private BigDecimal cprSumm;

	private Short cprNdsByString;

	private BigDecimal cprSumAssembling;

	private Set<DboCprListProduce> dclCprListProduces = new HashSet<DboCprListProduce>(
			0);

	public DclCommercialProposal() {
	}

	public DclCommercialProposal(int cprId, DclCurrency dclCurrency,
			DclContractor dclContractor, DboUser dclUserByUsrIdCreate,
			DboUser dclUserByUsrIdEdit,
			DclTermInco dclTermIncoByTrmIdDeliveryCondition,
			DclTermInco dclTermIncoByTrmIdPriceCondition, Date cprCreateDate,
			Date cprEditDate, String cprNumber, Date cprDate) {
		this.cprId = cprId;
		this.dclCurrency = dclCurrency;
		this.dclContractor = dclContractor;
		this.dclUserByUsrIdCreate = dclUserByUsrIdCreate;
		this.dclUserByUsrIdEdit = dclUserByUsrIdEdit;
		this.dclTermIncoByTrmIdDeliveryCondition = dclTermIncoByTrmIdDeliveryCondition;
		this.dclTermIncoByTrmIdPriceCondition = dclTermIncoByTrmIdPriceCondition;
		this.cprCreateDate = cprCreateDate;
		this.cprEditDate = cprEditDate;
		this.cprNumber = cprNumber;
		this.cprDate = cprDate;
	}

	public DclCommercialProposal(int cprId, DboUser dclUserByUsrId,
			DclCurrency dclCurrency, DclContractor dclContractor,
			DboUser dclUserByUsrIdCreate,
			DclContactPerson dclContactPerson, DboUser dclUserByUsrIdEdit,
			DclTermInco dclTermIncoByTrmIdDeliveryCondition,
			DclTermInco dclTermIncoByTrmIdPriceCondition, Date cprCreateDate,
			Date cprEditDate, String cprNumber, Date cprDate,
			String cprConcerning, String cprPreamble, BigDecimal cprCourse,
			BigDecimal cprNds, String cprCountry, String cprPayCondition,
			String cprDeliveryAddress, BigDecimal cprSumTransport,
			String cprDeliveryTerm, String cprAddInfo, Date cprFinalDate,
			Short cprProposalReceivedFlag, Date cprDateAccept, Short cprBlock,
			String cprImgName, BigDecimal cprSumm, Short cprNdsByString,
			BigDecimal cprSumAssembling,
			Set<DboCprListProduce> dclCprListProduces) {
		this.cprId = cprId;
		this.dclUserByUsrId = dclUserByUsrId;
		this.dclCurrency = dclCurrency;
		this.dclContractor = dclContractor;
		this.dclUserByUsrIdCreate = dclUserByUsrIdCreate;
		this.dclContactPerson = dclContactPerson;
		this.dclUserByUsrIdEdit = dclUserByUsrIdEdit;
		this.dclTermIncoByTrmIdDeliveryCondition = dclTermIncoByTrmIdDeliveryCondition;
		this.dclTermIncoByTrmIdPriceCondition = dclTermIncoByTrmIdPriceCondition;
		this.cprCreateDate = cprCreateDate;
		this.cprEditDate = cprEditDate;
		this.cprNumber = cprNumber;
		this.cprDate = cprDate;
		this.cprConcerning = cprConcerning;
		this.cprPreamble = cprPreamble;
		this.cprCourse = cprCourse;
		this.cprNds = cprNds;
		this.cprCountry = cprCountry;
		this.cprPayCondition = cprPayCondition;
		this.cprDeliveryAddress = cprDeliveryAddress;
		this.cprSumTransport = cprSumTransport;
		this.cprDeliveryTerm = cprDeliveryTerm;
		this.cprAddInfo = cprAddInfo;
		this.cprFinalDate = cprFinalDate;
		this.cprProposalReceivedFlag = cprProposalReceivedFlag;
		this.cprDateAccept = cprDateAccept;
		this.cprBlock = cprBlock;
		this.cprImgName = cprImgName;
		this.cprSumm = cprSumm;
		this.cprNdsByString = cprNdsByString;
		this.cprSumAssembling = cprSumAssembling;
		this.dclCprListProduces = dclCprListProduces;
	}

	@Id
	@Column(name = "CPR_ID", unique = true, nullable = false)
	public int getCprId() {
		return this.cprId;
	}

	public void setCprId(int cprId) {
		this.cprId = cprId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "USR_ID")
	public DboUser getDclUserByUsrId() {
		return this.dclUserByUsrId;
	}

	public void setDclUserByUsrId(DboUser dclUserByUsrId) {
		this.dclUserByUsrId = dclUserByUsrId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CUR_ID", nullable = false)
	public DclCurrency getDclCurrency() {
		return this.dclCurrency;
	}

	public void setDclCurrency(DclCurrency dclCurrency) {
		this.dclCurrency = dclCurrency;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CTR_ID", nullable = false)
	public DclContractor getDclContractor() {
		return this.dclContractor;
	}

	public void setDclContractor(DclContractor dclContractor) {
		this.dclContractor = dclContractor;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "USR_ID_CREATE", nullable = false)
	public DboUser getDclUserByUsrIdCreate() {
		return this.dclUserByUsrIdCreate;
	}

	public void setDclUserByUsrIdCreate(DboUser dclUserByUsrIdCreate) {
		this.dclUserByUsrIdCreate = dclUserByUsrIdCreate;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CPS_ID")
	public DclContactPerson getDclContactPerson() {
		return this.dclContactPerson;
	}

	public void setDclContactPerson(DclContactPerson dclContactPerson) {
		this.dclContactPerson = dclContactPerson;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "USR_ID_EDIT", nullable = false)
	public DboUser getDclUserByUsrIdEdit() {
		return this.dclUserByUsrIdEdit;
	}

	public void setDclUserByUsrIdEdit(DboUser dclUserByUsrIdEdit) {
		this.dclUserByUsrIdEdit = dclUserByUsrIdEdit;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TRM_ID_DELIVERY_CONDITION", nullable = false)
	public DclTermInco getDclTermIncoByTrmIdDeliveryCondition() {
		return this.dclTermIncoByTrmIdDeliveryCondition;
	}

	public void setDclTermIncoByTrmIdDeliveryCondition(
			DclTermInco dclTermIncoByTrmIdDeliveryCondition) {
		this.dclTermIncoByTrmIdDeliveryCondition = dclTermIncoByTrmIdDeliveryCondition;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TRM_ID_PRICE_CONDITION", nullable = false)
	public DclTermInco getDclTermIncoByTrmIdPriceCondition() {
		return this.dclTermIncoByTrmIdPriceCondition;
	}

	public void setDclTermIncoByTrmIdPriceCondition(
			DclTermInco dclTermIncoByTrmIdPriceCondition) {
		this.dclTermIncoByTrmIdPriceCondition = dclTermIncoByTrmIdPriceCondition;
	}

	@Column(name = "CPR_CREATE_DATE", nullable = false, length = 19)
	public Date getCprCreateDate() {
		return this.cprCreateDate;
	}

	public void setCprCreateDate(Date cprCreateDate) {
		this.cprCreateDate = cprCreateDate;
	}

	@Column(name = "CPR_EDIT_DATE", nullable = false, length = 19)
	public Date getCprEditDate() {
		return this.cprEditDate;
	}

	public void setCprEditDate(Date cprEditDate) {
		this.cprEditDate = cprEditDate;
	}

	@Column(name = "CPR_NUMBER", nullable = false, length = 15)
	public String getCprNumber() {
		return this.cprNumber;
	}

	public void setCprNumber(String cprNumber) {
		this.cprNumber = cprNumber;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CPR_DATE", nullable = false, length = 10)
	public Date getCprDate() {
		return this.cprDate;
	}

	public void setCprDate(Date cprDate) {
		this.cprDate = cprDate;
	}

	@Column(name = "CPR_CONCERNING", length = 1000)
	public String getCprConcerning() {
		return this.cprConcerning;
	}

	public void setCprConcerning(String cprConcerning) {
		this.cprConcerning = cprConcerning;
	}

	@Column(name = "CPR_PREAMBLE", length = 1000)
	public String getCprPreamble() {
		return this.cprPreamble;
	}

	public void setCprPreamble(String cprPreamble) {
		this.cprPreamble = cprPreamble;
	}

	@Column(name = "CPR_COURSE", precision = 15)
	public BigDecimal getCprCourse() {
		return this.cprCourse;
	}

	public void setCprCourse(BigDecimal cprCourse) {
		this.cprCourse = cprCourse;
	}

	@Column(name = "CPR_NDS", precision = 15)
	public BigDecimal getCprNds() {
		return this.cprNds;
	}

	public void setCprNds(BigDecimal cprNds) {
		this.cprNds = cprNds;
	}

	@Column(name = "CPR_COUNTRY", length = 32)
	public String getCprCountry() {
		return this.cprCountry;
	}

	public void setCprCountry(String cprCountry) {
		this.cprCountry = cprCountry;
	}

	@Column(name = "CPR_PAY_CONDITION", length = 1000)
	public String getCprPayCondition() {
		return this.cprPayCondition;
	}

	public void setCprPayCondition(String cprPayCondition) {
		this.cprPayCondition = cprPayCondition;
	}

	@Column(name = "CPR_DELIVERY_ADDRESS", length = 256)
	public String getCprDeliveryAddress() {
		return this.cprDeliveryAddress;
	}

	public void setCprDeliveryAddress(String cprDeliveryAddress) {
		this.cprDeliveryAddress = cprDeliveryAddress;
	}

	@Column(name = "CPR_SUM_TRANSPORT", precision = 15)
	public BigDecimal getCprSumTransport() {
		return this.cprSumTransport;
	}

	public void setCprSumTransport(BigDecimal cprSumTransport) {
		this.cprSumTransport = cprSumTransport;
	}

	@Column(name = "CPR_DELIVERY_TERM", length = 2000)
	public String getCprDeliveryTerm() {
		return this.cprDeliveryTerm;
	}

	public void setCprDeliveryTerm(String cprDeliveryTerm) {
		this.cprDeliveryTerm = cprDeliveryTerm;
	}

	@Column(name = "CPR_ADD_INFO", length = 3000)
	public String getCprAddInfo() {
		return this.cprAddInfo;
	}

	public void setCprAddInfo(String cprAddInfo) {
		this.cprAddInfo = cprAddInfo;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CPR_FINAL_DATE", length = 10)
	public Date getCprFinalDate() {
		return this.cprFinalDate;
	}

	public void setCprFinalDate(Date cprFinalDate) {
		this.cprFinalDate = cprFinalDate;
	}

	@Column(name = "CPR_PROPOSAL_RECEIVED_FLAG")
	public Short getCprProposalReceivedFlag() {
		return this.cprProposalReceivedFlag;
	}

	public void setCprProposalReceivedFlag(Short cprProposalReceivedFlag) {
		this.cprProposalReceivedFlag = cprProposalReceivedFlag;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CPR_DATE_ACCEPT", length = 10)
	public Date getCprDateAccept() {
		return this.cprDateAccept;
	}

	public void setCprDateAccept(Date cprDateAccept) {
		this.cprDateAccept = cprDateAccept;
	}

	@Column(name = "CPR_BLOCK")
	public Short getCprBlock() {
		return this.cprBlock;
	}

	public void setCprBlock(Short cprBlock) {
		this.cprBlock = cprBlock;
	}

	@Column(name = "CPR_IMG_NAME", length = 20)
	public String getCprImgName() {
		return this.cprImgName;
	}

	public void setCprImgName(String cprImgName) {
		this.cprImgName = cprImgName;
	}

	@Column(name = "CPR_SUMM", precision = 15)
	public BigDecimal getCprSumm() {
		return this.cprSumm;
	}

	public void setCprSumm(BigDecimal cprSumm) {
		this.cprSumm = cprSumm;
	}

	@Column(name = "CPR_NDS_BY_STRING")
	public Short getCprNdsByString() {
		return this.cprNdsByString;
	}

	public void setCprNdsByString(Short cprNdsByString) {
		this.cprNdsByString = cprNdsByString;
	}

	@Column(name = "CPR_SUM_ASSEMBLING", precision = 15)
	public BigDecimal getCprSumAssembling() {
		return this.cprSumAssembling;
	}

	public void setCprSumAssembling(BigDecimal cprSumAssembling) {
		this.cprSumAssembling = cprSumAssembling;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "commercialProposal")
	public Set<DboCprListProduce> getDclCprListProduces() {
		return this.dclCprListProduces;
	}

	public void setDclCprListProduces(Set<DboCprListProduce> dclCprListProduces) {
		this.dclCprListProduces = dclCprListProduces;
	}

}
