package net.sam.dcl.dbo.dirty;

// Generated 23-May-2007 22:53:40 by Hibernate Tools 3.2.0.b9

import net.sam.dcl.dbo.DboUser;

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DclContract generated by hbm2java
 */
@Entity
@Table(name = "DCL_CONTRACT")
public class DclContract implements java.io.Serializable {

	private int conId;

	private DclCurrency dclCurrency;

	private DclContractor dclContractor;

	private DboUser dclUserByUsrIdCreate;

	private DboUser dclUserByUsrIdEdit;

	private Date conCreateDate;

	private Date conEditDate;

	private String conNumber;

	private Date conDate;

	private Short conExecuted;

	private BigDecimal conSumm;

	private Short conOriginal;

	private Set<DclConListSpec> dclConListSpecs = new HashSet<DclConListSpec>(0);

	public DclContract() {
	}

	public DclContract(int conId) {
		this.conId = conId;
	}

	public DclContract(int conId, DclCurrency dclCurrency,
			DclContractor dclContractor, DboUser dclUserByUsrIdCreate,
			DboUser dclUserByUsrIdEdit, Date conCreateDate, Date conEditDate,
			String conNumber, Date conDate, Short conExecuted,
			BigDecimal conSumm, Short conOriginal,
			Set<DclConListSpec> dclConListSpecs) {
		this.conId = conId;
		this.dclCurrency = dclCurrency;
		this.dclContractor = dclContractor;
		this.dclUserByUsrIdCreate = dclUserByUsrIdCreate;
		this.dclUserByUsrIdEdit = dclUserByUsrIdEdit;
		this.conCreateDate = conCreateDate;
		this.conEditDate = conEditDate;
		this.conNumber = conNumber;
		this.conDate = conDate;
		this.conExecuted = conExecuted;
		this.conSumm = conSumm;
		this.conOriginal = conOriginal;
		this.dclConListSpecs = dclConListSpecs;
	}

	@Id
	@Column(name = "CON_ID", unique = true, nullable = false)
	public int getConId() {
		return this.conId;
	}

	public void setConId(int conId) {
		this.conId = conId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CUR_ID")
	public DclCurrency getDclCurrency() {
		return this.dclCurrency;
	}

	public void setDclCurrency(DclCurrency dclCurrency) {
		this.dclCurrency = dclCurrency;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CTR_ID")
	public DclContractor getDclContractor() {
		return this.dclContractor;
	}

	public void setDclContractor(DclContractor dclContractor) {
		this.dclContractor = dclContractor;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "USR_ID_CREATE")
	public DboUser getDclUserByUsrIdCreate() {
		return this.dclUserByUsrIdCreate;
	}

	public void setDclUserByUsrIdCreate(DboUser dclUserByUsrIdCreate) {
		this.dclUserByUsrIdCreate = dclUserByUsrIdCreate;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "USR_ID_EDIT")
	public DboUser getDclUserByUsrIdEdit() {
		return this.dclUserByUsrIdEdit;
	}

	public void setDclUserByUsrIdEdit(DboUser dclUserByUsrIdEdit) {
		this.dclUserByUsrIdEdit = dclUserByUsrIdEdit;
	}

	@Column(name = "CON_CREATE_DATE", length = 19)
	public Date getConCreateDate() {
		return this.conCreateDate;
	}

	public void setConCreateDate(Date conCreateDate) {
		this.conCreateDate = conCreateDate;
	}

	@Column(name = "CON_EDIT_DATE", length = 19)
	public Date getConEditDate() {
		return this.conEditDate;
	}

	public void setConEditDate(Date conEditDate) {
		this.conEditDate = conEditDate;
	}

	@Column(name = "CON_NUMBER", length = 50)
	public String getConNumber() {
		return this.conNumber;
	}

	public void setConNumber(String conNumber) {
		this.conNumber = conNumber;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CON_DATE", length = 10)
	public Date getConDate() {
		return this.conDate;
	}

	public void setConDate(Date conDate) {
		this.conDate = conDate;
	}

	@Column(name = "CON_EXECUTED")
	public Short getConExecuted() {
		return this.conExecuted;
	}

	public void setConExecuted(Short conExecuted) {
		this.conExecuted = conExecuted;
	}

	@Column(name = "CON_SUMM", precision = 15)
	public BigDecimal getConSumm() {
		return this.conSumm;
	}

	public void setConSumm(BigDecimal conSumm) {
		this.conSumm = conSumm;
	}

	@Column(name = "CON_ORIGINAL")
	public Short getConOriginal() {
		return this.conOriginal;
	}

	public void setConOriginal(Short conOriginal) {
		this.conOriginal = conOriginal;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "dclContract")
	public Set<DclConListSpec> getDclConListSpecs() {
		return this.dclConListSpecs;
	}

	public void setDclConListSpecs(Set<DclConListSpec> dclConListSpecs) {
		this.dclConListSpecs = dclConListSpecs;
	}

}
