package net.sam.dcl.dbo.dirty;

// Generated 23-May-2007 22:53:40 by Hibernate Tools 3.2.0.b9

import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * DclCurrency generated by hbm2java
 */
@Entity
@Table(name = "DCL_CURRENCY")
public class DclCurrency implements java.io.Serializable {

	private int curId;

	private String curName;

	private Short curNoRound;

	private Set<DclPayment> dclPayments = new HashSet<DclPayment>(0);

	private Set<DclContract> dclContracts = new HashSet<DclContract>(0);

	private Set<DclShipping> dclShippings = new HashSet<DclShipping>(0);

	private Set<DclCommercialProposal> dclCommercialProposals = new HashSet<DclCommercialProposal>(
			0);

	public DclCurrency() {
	}

	public DclCurrency(int curId, String curName) {
		this.curId = curId;
		this.curName = curName;
	}

	public DclCurrency(int curId, String curName, Short curNoRound,
			Set<DclPayment> dclPayments, Set<DclContract> dclContracts,
			Set<DclShipping> dclShippings,
			Set<DclCommercialProposal> dclCommercialProposals) {
		this.curId = curId;
		this.curName = curName;
		this.curNoRound = curNoRound;
		this.dclPayments = dclPayments;
		this.dclContracts = dclContracts;
		this.dclShippings = dclShippings;
		this.dclCommercialProposals = dclCommercialProposals;
	}

	@Id
	@Column(name = "CUR_ID", unique = true, nullable = false)
	public int getCurId() {
		return this.curId;
	}

	public void setCurId(int curId) {
		this.curId = curId;
	}

	@Column(name = "CUR_NAME", nullable = false, length = 10)
	public String getCurName() {
		return this.curName;
	}

	public void setCurName(String curName) {
		this.curName = curName;
	}

	@Column(name = "CUR_NO_ROUND")
	public Short getCurNoRound() {
		return this.curNoRound;
	}

	public void setCurNoRound(Short curNoRound) {
		this.curNoRound = curNoRound;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "dclCurrency")
	public Set<DclPayment> getDclPayments() {
		return this.dclPayments;
	}

	public void setDclPayments(Set<DclPayment> dclPayments) {
		this.dclPayments = dclPayments;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "dclCurrency")
	public Set<DclContract> getDclContracts() {
		return this.dclContracts;
	}

	public void setDclContracts(Set<DclContract> dclContracts) {
		this.dclContracts = dclContracts;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "dclCurrency")
	public Set<DclShipping> getDclShippings() {
		return this.dclShippings;
	}

	public void setDclShippings(Set<DclShipping> dclShippings) {
		this.dclShippings = dclShippings;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "dclCurrency")
	public Set<DclCommercialProposal> getDclCommercialProposals() {
		return this.dclCommercialProposals;
	}

	public void setDclCommercialProposals(
			Set<DclCommercialProposal> dclCommercialProposals) {
		this.dclCommercialProposals = dclCommercialProposals;
	}

}
