package net.sam.dcl.dbo.dirty;

// Generated 23-May-2007 22:53:40 by Hibernate Tools 3.2.0.b9

import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * DclContactPerson generated by hbm2java
 */
@Entity
@Table(name = "DCL_CONTACT_PERSON")
public class DclContactPerson implements java.io.Serializable {

	private int cpsId;

	private DclContractor dclContractor;

	private String cpsName;

	private String cpsPhone;

	private String cpsFax;

	private Short cpsBlock;

	private Set<DclCommercialProposal> dclCommercialProposals = new HashSet<DclCommercialProposal>(
			0);

	public DclContactPerson() {
	}

	public DclContactPerson(int cpsId, DclContractor dclContractor) {
		this.cpsId = cpsId;
		this.dclContractor = dclContractor;
	}

	public DclContactPerson(int cpsId, DclContractor dclContractor,
			String cpsName, String cpsPhone, String cpsFax, Short cpsBlock,
			Set<DclCommercialProposal> dclCommercialProposals) {
		this.cpsId = cpsId;
		this.dclContractor = dclContractor;
		this.cpsName = cpsName;
		this.cpsPhone = cpsPhone;
		this.cpsFax = cpsFax;
		this.cpsBlock = cpsBlock;
		this.dclCommercialProposals = dclCommercialProposals;
	}

	@Id
	@Column(name = "CPS_ID", unique = true, nullable = false)
	public int getCpsId() {
		return this.cpsId;
	}

	public void setCpsId(int cpsId) {
		this.cpsId = cpsId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CTR_ID", nullable = false)
	public DclContractor getDclContractor() {
		return this.dclContractor;
	}

	public void setDclContractor(DclContractor dclContractor) {
		this.dclContractor = dclContractor;
	}

	@Column(name = "CPS_NAME", length = 200)
	public String getCpsName() {
		return this.cpsName;
	}

	public void setCpsName(String cpsName) {
		this.cpsName = cpsName;
	}

	@Column(name = "CPS_PHONE", length = 150)
	public String getCpsPhone() {
		return this.cpsPhone;
	}

	public void setCpsPhone(String cpsPhone) {
		this.cpsPhone = cpsPhone;
	}

	@Column(name = "CPS_FAX", length = 150)
	public String getCpsFax() {
		return this.cpsFax;
	}

	public void setCpsFax(String cpsFax) {
		this.cpsFax = cpsFax;
	}

	@Column(name = "CPS_BLOCK")
	public Short getCpsBlock() {
		return this.cpsBlock;
	}

	public void setCpsBlock(Short cpsBlock) {
		this.cpsBlock = cpsBlock;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "dclContactPerson")
	public Set<DclCommercialProposal> getDclCommercialProposals() {
		return this.dclCommercialProposals;
	}

	public void setDclCommercialProposals(
			Set<DclCommercialProposal> dclCommercialProposals) {
		this.dclCommercialProposals = dclCommercialProposals;
	}

}
