package net.sam.dcl.dbo.dirty;

// Generated 23-May-2007 22:53:40 by Hibernate Tools 3.2.0.b9

import net.sam.dcl.dbo.DboStuffCategory;
import net.sam.dcl.dbo.DboDeliveryRequest;
import net.sam.dcl.dbo.DboProduce;

import java.math.BigDecimal;
import java.util.Set;
import java.util.HashSet;
import javax.persistence.*;

/**
 * DclDlrListProduce generated by hbm2java
 */
@Entity
@Table(name = "DCL_DLR_LIST_PRODUCE")
public class DclDlrListProduce implements java.io.Serializable {
	@Id
	@Column(name = "DRP_ID", unique = true, nullable = false)
	private int drpId;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "STF_ID")
	private DboStuffCategory stuffCategory;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "OPR_ID")
	private DclOrdListProduce dclOrdListProduce;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DLR_ID", nullable = false)
	private DboDeliveryRequest deliveryRequest;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CTR_ID")
	private DclContractor dclContractor;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PRS_ID")
	private DclPurpose dclPurpose;

	@Column(name = "DRP_PRICE", nullable = false, precision = 15)
	private BigDecimal price;

	@Column(name = "DRP_COUNT", nullable = false, precision = 15)
	private BigDecimal count;

	@Column(name = "DRP_PURPOSE", length = 500)
	private String purpose;
	                                                   
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PRD_ID")
	private DboProduce produce;

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "dclDlrListProduce")
	private Set<DclSpiListProduce> dclSpiListProduces = new HashSet<DclSpiListProduce>(0);

	public DclDlrListProduce() {
	}

	public DclDlrListProduce(int drpId, DboDeliveryRequest deliveryRequest,
			BigDecimal price, BigDecimal count) {
		this.drpId = drpId;
		this.deliveryRequest = deliveryRequest;
		this.price = price;
		this.count = count;
	}

	public DclDlrListProduce(int drpId, DboStuffCategory dboStuffCategory,
			DclOrdListProduce dclOrdListProduce,
			DboDeliveryRequest deliveryRequest, DclContractor dclContractor,
			DclPurpose dclPurpose, BigDecimal price, BigDecimal count,
			String purpose) {
		this.drpId = drpId;
		this.stuffCategory = dboStuffCategory;
		this.dclOrdListProduce = dclOrdListProduce;
		this.deliveryRequest = deliveryRequest;
		this.dclContractor = dclContractor;
		this.dclPurpose = dclPurpose;
		this.price = price;
		this.count = count;
		this.purpose = purpose;
	}

	public int getDrpId() {
		return this.drpId;
	}

	public void setDrpId(int drpId) {
		this.drpId = drpId;
	}

	public DboStuffCategory getStuffCategory() {
		return this.stuffCategory;
	}

	public void setStuffCategory(DboStuffCategory dboStuffCategory) {
		this.stuffCategory = dboStuffCategory;
	}

	public DclOrdListProduce getDclOrdListProduce() {
		return this.dclOrdListProduce;
	}

	public void setDclOrdListProduce(DclOrdListProduce dclOrdListProduce) {
		this.dclOrdListProduce = dclOrdListProduce;
	}

	public DboDeliveryRequest getDboDeliveryRequest() {
		return this.deliveryRequest;
	}

	public void setDboDeliveryRequest(DboDeliveryRequest dboDeliveryRequest) {
		this.deliveryRequest = dboDeliveryRequest;
	}

	public DclContractor getDclContractor() {
		return this.dclContractor;
	}

	public void setDclContractor(DclContractor dclContractor) {
		this.dclContractor = dclContractor;
	}

	public DclPurpose getDclPurpose() {
		return this.dclPurpose;
	}

	public void setDclPurpose(DclPurpose dclPurpose) {
		this.dclPurpose = dclPurpose;
	}


	public BigDecimal getPrice() {
		return this.price;
	}

	public void setPrice(BigDecimal price) {
		this.price = price;
	}


	public BigDecimal getCount() {
		return this.count;
	}

	public void setCount(BigDecimal count) {
		this.count = count;
	}


	public String getPurpose() {
		return this.purpose;
	}

	public void setPurpose(String purpose) {
		this.purpose = purpose;
	}


	public DboProduce getProduce() {
		return produce;
	}

	public void setProduce(DboProduce produce) {
		this.produce = produce;
	}

	public Set<DclSpiListProduce> getDclSpiListProduces() {
		return this.dclSpiListProduces;
	}

	public void setDclSpiListProduces(Set<DclSpiListProduce> dclSpiListProduces) {
		this.dclSpiListProduces = dclSpiListProduces;
	}

}
