package net.sam.dcl.dbo.dirty;

// Generated 23-May-2007 22:53:40 by Hibernate Tools 3.2.0.b9

import net.sam.dcl.dbo.DboUser;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * DclDepartment generated by hbm2java
 */
@Entity
@Table(name = "DCL_DEPARTMENT")
public class DclDepartment implements java.io.Serializable {

	private int depId;

	private String depName;

	private Set<DboUser> dclUsers = new HashSet<DboUser>(0);

	public DclDepartment() {
	}

	public DclDepartment(int depId, String depName) {
		this.depId = depId;
		this.depName = depName;
	}

	public DclDepartment(int depId, String depName, Set<DboUser> dclUsers) {
		this.depId = depId;
		this.depName = depName;
		this.dclUsers = dclUsers;
	}

	@Id
	@Column(name = "DEP_ID", unique = true, nullable = false)
	public int getDepId() {
		return this.depId;
	}

	public void setDepId(int depId) {
		this.depId = depId;
	}

	@Column(name = "DEP_NAME", nullable = false, length = 20)
	public String getDepName() {
		return this.depName;
	}

	public void setDepName(String depName) {
		this.depName = depName;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "department")
	public Set<DboUser> getDclUsers() {
		return this.dclUsers;
	}

	public void setDclUsers(Set<DboUser> dclUsers) {
		this.dclUsers = dclUsers;
	}

}
