package net.sam.dcl.dbo.dirty;

// Generated 23-May-2007 22:53:40 by Hibernate Tools 3.2.0.b9

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * DclOccupiedPrcProduceV generated by hbm2java
 */
@Entity
@Table(name = "DCL_OCCUPIED_PRC_PRODUCE_V")
public class DclOccupiedPrcProduceV implements java.io.Serializable {

	private Integer lpcId;

	public DclOccupiedPrcProduceV() {
	}

	public DclOccupiedPrcProduceV(Integer lpcId) {
		this.lpcId = lpcId;
	}

	@Id
	@Column(name = "LPC_ID")
	public Integer getLpcId() {
		return this.lpcId;
	}

	public void setLpcId(Integer lpcId) {
		this.lpcId = lpcId;
	}

}
