package net.sam.dcl.dbo.dirty;

// Generated 23-May-2007 22:53:40 by Hibernate Tools 3.2.0.b9

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * DclOccupiedContractV generated by hbm2java
 */
@Entity
@Table(name = "DCL_OCCUPIED_CONTRACT_V")
public class DclOccupiedContractV implements java.io.Serializable {

	private Integer conId;

	public DclOccupiedContractV() {
	}

	public DclOccupiedContractV(Integer conId) {
		this.conId = conId;
	}

	@Id
	@Column(name = "CON_ID")
	public Integer getConId() {
		return this.conId;
	}

	public void setConId(Integer conId) {
		this.conId = conId;
	}

}
