package net.sam.dcl.dbo.dirty;

// Generated 23-May-2007 22:53:40 by Hibernate Tools 3.2.0.b9

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * DclOccupiedSpecV generated by hbm2java
 */
@Entity
@Table(name = "DCL_OCCUPIED_SPEC_V")
public class DclOccupiedSpecV implements java.io.Serializable {

	private Integer spcId;

	public DclOccupiedSpecV() {
	}

	public DclOccupiedSpecV(Integer spcId) {
		this.spcId = spcId;
	}

	@Id
	@Column(name = "SPC_ID")
	public Integer getSpcId() {
		return this.spcId;
	}

	public void setSpcId(Integer spcId) {
		this.spcId = spcId;
	}

}
