package net.sam.dcl.dbo.dirty;

// Generated 23-May-2007 22:53:40 by Hibernate Tools 3.2.0.b9

import net.sam.dcl.dbo.DboProduce;

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * DclOrdListProduce generated by hbm2java
 */
@Entity
@Table(name = "DCL_ORD_LIST_PRODUCE")
public class DclOrdListProduce implements java.io.Serializable {
	@Id
	@Column(name = "OPR_ID", unique = true, nullable = false)
	private int oprId;

	private String oprProduceName;

	private String oprCatalogNum;

	private BigDecimal oprCount;

	private BigDecimal oprPriceBrutto;

	private BigDecimal oprDiscount;

	private BigDecimal oprPriceNetto;

	private BigDecimal oprSumm;

	private Character oprUsePrevNumber;

  @ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PRD_ID")
	private DboProduce produce;

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "dclOrdListProduce")
	private Set<DclDlrListProduce> dclDlrListProduces = new HashSet<DclDlrListProduce>();

	public DclOrdListProduce() {
	}

	public DclOrdListProduce(int oprId, String oprProduceName) {
		this.oprId = oprId;
		this.oprProduceName = oprProduceName;
	}

	public DclOrdListProduce(int oprId,
			String oprProduceName, String oprCatalogNum, BigDecimal oprCount,
			BigDecimal oprPriceBrutto, BigDecimal oprDiscount,
			BigDecimal oprPriceNetto, BigDecimal oprSumm,
			Character oprUsePrevNumber,
			Set<DclDlrListProduce> dclDlrListProduces) {
		this.oprId = oprId;
		this.oprProduceName = oprProduceName;
		this.oprCatalogNum = oprCatalogNum;
		this.oprCount = oprCount;
		this.oprPriceBrutto = oprPriceBrutto;
		this.oprDiscount = oprDiscount;
		this.oprPriceNetto = oprPriceNetto;
		this.oprSumm = oprSumm;
		this.oprUsePrevNumber = oprUsePrevNumber;
		this.dclDlrListProduces = dclDlrListProduces;
	}

	public int getOprId() {
		return this.oprId;
	}

	public void setOprId(int oprId) {
		this.oprId = oprId;
	}

	@Column(name = "OPR_PRODUCE_NAME", nullable = false, length = 1000)
	public String getOprProduceName() {
		return this.oprProduceName;
	}

	public void setOprProduceName(String oprProduceName) {
		this.oprProduceName = oprProduceName;
	}

	@Column(name = "OPR_CATALOG_NUM", length = 50)
	public String getOprCatalogNum() {
		return this.oprCatalogNum;
	}

	public void setOprCatalogNum(String oprCatalogNum) {
		this.oprCatalogNum = oprCatalogNum;
	}

	@Column(name = "OPR_COUNT", precision = 15)
	public BigDecimal getOprCount() {
		return this.oprCount;
	}

	public void setOprCount(BigDecimal oprCount) {
		this.oprCount = oprCount;
	}

	@Column(name = "OPR_PRICE_BRUTTO", precision = 15)
	public BigDecimal getOprPriceBrutto() {
		return this.oprPriceBrutto;
	}

	public void setOprPriceBrutto(BigDecimal oprPriceBrutto) {
		this.oprPriceBrutto = oprPriceBrutto;
	}

	@Column(name = "OPR_DISCOUNT", precision = 15)
	public BigDecimal getOprDiscount() {
		return this.oprDiscount;
	}

	public void setOprDiscount(BigDecimal oprDiscount) {
		this.oprDiscount = oprDiscount;
	}

	@Column(name = "OPR_PRICE_NETTO", precision = 15)
	public BigDecimal getOprPriceNetto() {
		return this.oprPriceNetto;
	}

	public void setOprPriceNetto(BigDecimal oprPriceNetto) {
		this.oprPriceNetto = oprPriceNetto;
	}

	@Column(name = "OPR_SUMM", precision = 15)
	public BigDecimal getOprSumm() {
		return this.oprSumm;
	}

	public void setOprSumm(BigDecimal oprSumm) {
		this.oprSumm = oprSumm;
	}

	@Column(name = "OPR_USE_PREV_NUMBER", length = 1)
	public Character getOprUsePrevNumber() {
		return this.oprUsePrevNumber;
	}

	public void setOprUsePrevNumber(Character oprUsePrevNumber) {
		this.oprUsePrevNumber = oprUsePrevNumber;
	}


	public Set<DclDlrListProduce> getDclDlrListProduces() {
		return this.dclDlrListProduces;
	}

	public void setDclDlrListProduces(Set<DclDlrListProduce> dclDlrListProduces) {
		this.dclDlrListProduces = dclDlrListProduces;
	}

	public DboProduce getProduce() {
		return produce;
	}

	public void setProduce(DboProduce produce) {
		this.produce = produce;
	}
}
