package net.sam.dcl.dbo.dirty;

// Generated 23-May-2007 22:53:40 by Hibernate Tools 3.2.0.b9

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * DclOccupiedContractorV generated by hbm2java
 */
@Entity
@Table(name = "DCL_OCCUPIED_CONTRACTOR_V")
public class DclOccupiedContractorV implements java.io.Serializable {

	private Integer ctrId;

	public DclOccupiedContractorV() {
	}

	public DclOccupiedContractorV(Integer ctrId) {
		this.ctrId = ctrId;
	}

	@Id
	@Column(name = "CTR_ID")
	public Integer getCtrId() {
		return this.ctrId;
	}

	public void setCtrId(Integer ctrId) {
		this.ctrId = ctrId;
	}

}
