package net.sam.dcl.dbo.dirty;

// Generated 23-May-2007 22:53:40 by Hibernate Tools 3.2.0.b9

import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * DclPurpose generated by hbm2java
 */
@Entity
@Table(name = "DCL_PURPOSE")
public class DclPurpose implements java.io.Serializable {

	private int prsId;

	private String prsName;

	private Set<DclDlrListProduce> dclDlrListProduces = new HashSet<DclDlrListProduce>(
			0);

	private Set<DclPrcListProduce> dclPrcListProduces = new HashSet<DclPrcListProduce>(
			0);

	public DclPurpose() {
	}

	public DclPurpose(int prsId) {
		this.prsId = prsId;
	}

	public DclPurpose(int prsId, String prsName,
			Set<DclDlrListProduce> dclDlrListProduces,
			Set<DclPrcListProduce> dclPrcListProduces) {
		this.prsId = prsId;
		this.prsName = prsName;
		this.dclDlrListProduces = dclDlrListProduces;
		this.dclPrcListProduces = dclPrcListProduces;
	}

	@Id
	@Column(name = "PRS_ID", unique = true, nullable = false)
	public int getPrsId() {
		return this.prsId;
	}

	public void setPrsId(int prsId) {
		this.prsId = prsId;
	}

	@Column(name = "PRS_NAME", length = 200)
	public String getPrsName() {
		return this.prsName;
	}

	public void setPrsName(String prsName) {
		this.prsName = prsName;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "dclPurpose")
	public Set<DclDlrListProduce> getDclDlrListProduces() {
		return this.dclDlrListProduces;
	}

	public void setDclDlrListProduces(Set<DclDlrListProduce> dclDlrListProduces) {
		this.dclDlrListProduces = dclDlrListProduces;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "dclPurpose")
	public Set<DclPrcListProduce> getDclPrcListProduces() {
		return this.dclPrcListProduces;
	}

	public void setDclPrcListProduces(Set<DclPrcListProduce> dclPrcListProduces) {
		this.dclPrcListProduces = dclPrcListProduces;
	}

}
