package net.sam.dcl.dbo.dirty;

// Generated 23-May-2007 22:53:40 by Hibernate Tools 3.2.0.b9

import net.sam.dcl.dbo.DboStuffCategory;
import net.sam.dcl.dbo.DboProduce;
import net.sam.dcl.dbo.DboUser;

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * DclPrcListProduce generated by hbm2java
 */
@Entity
@Table(name = "DCL_PRC_LIST_PRODUCE")
public class DclPrcListProduce implements java.io.Serializable {

	private int lpcId;

	private DboUser dclUser;

	private DboStuffCategory stuffCategory;

	private DclPurpose dclPurpose;

	private String lpcProduceName;

	private BigDecimal lpcCount;

	private BigDecimal lpcCostOneLtl;

	private BigDecimal lpcCostOne;

	private BigDecimal lpcWeight;

	private BigDecimal lpcSumm;

	private BigDecimal lpcSumTransport;

	private BigDecimal lpcCustom;

	private Set<DclShpListProduce> dclShpListProduces = new HashSet<DclShpListProduce>(
			0);
	private DboProduce produce;

	public DclPrcListProduce() {
	}

	public DclPrcListProduce(int lpcId,
			DclPurpose dclPurpose) {
		this.lpcId = lpcId;
		this.dclPurpose = dclPurpose;
	}

	public DclPrcListProduce(int lpcId,
			DboUser dclUser, DboStuffCategory dboStuffCategory,
			DclPurpose dclPurpose, String lpcProduceName,
			BigDecimal lpcCount, BigDecimal lpcCostOneLtl, BigDecimal lpcCostOne, BigDecimal lpcWeight,
			BigDecimal lpcSumm,
			BigDecimal lpcSumTransport, BigDecimal lpcCustom,
			Set<DclShpListProduce> dclShpListProduces) {
		this.lpcId = lpcId;
		this.dclUser = dclUser;
		this.stuffCategory = dboStuffCategory;
		this.dclPurpose = dclPurpose;
		this.lpcProduceName = lpcProduceName;
		this.lpcCount = lpcCount;
		this.lpcCostOneLtl = lpcCostOneLtl;
		this.lpcCostOne = lpcCostOne;
		this.lpcWeight = lpcWeight;
		this.lpcSumm = lpcSumm;
		this.lpcSumTransport = lpcSumTransport;
		this.lpcCustom = lpcCustom;
		this.dclShpListProduces = dclShpListProduces;
	}

	@Id
	@Column(name = "LPC_ID", unique = true, nullable = false)
	public int getLpcId() {
		return this.lpcId;
	}

	public void setLpcId(int lpcId) {
		this.lpcId = lpcId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "USR_ID")
	public DboUser getDclUser() {
		return this.dclUser;
	}

	public void setDclUser(DboUser dclUser) {
		this.dclUser = dclUser;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "STF_ID")
	public DboStuffCategory getStuffCategory() {
		return this.stuffCategory;
	}

	public void setStuffCategory(DboStuffCategory dboStuffCategory) {
		this.stuffCategory = dboStuffCategory;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PRS_ID", nullable = false)
	public DclPurpose getDclPurpose() {
		return this.dclPurpose;
	}

	public void setDclPurpose(DclPurpose dclPurpose) {
		this.dclPurpose = dclPurpose;
	}

	@Column(name = "LPC_PRODUCE_NAME", length = 1000)
	public String getLpcProduceName() {
		return this.lpcProduceName;
	}

	public void setLpcProduceName(String lpcProduceName) {
		this.lpcProduceName = lpcProduceName;
	}

	@Column(name = "LPC_COUNT", precision = 15)
	public BigDecimal getLpcCount() {
		return this.lpcCount;
	}

	public void setLpcCount(BigDecimal lpcCount) {
		this.lpcCount = lpcCount;
	}

	@Column(name = "LPC_COST_ONE_LTL", precision = 15)
	public BigDecimal getLpcCostOneLtl() {
		return this.lpcCostOneLtl;
	}

	public void setLpcCostOneLtl(BigDecimal lpcCostOneLtl) {
		this.lpcCostOneLtl = lpcCostOneLtl;
	}

	@Column(name = "LPC_COST_ONE", precision = 15)
	public BigDecimal getLpcCostOne() {
		return this.lpcCostOne;
	}

	public void setLpcCostOne(BigDecimal lpcCostOne) {
		this.lpcCostOne = lpcCostOne;
	}

	@Column(name = "LPC_WEIGHT", precision = 15, scale = 3)
	public BigDecimal getLpcWeight() {
		return this.lpcWeight;
	}

	public void setLpcWeight(BigDecimal lpcWeight) {
		this.lpcWeight = lpcWeight;
	}

	@Column(name = "LPC_SUMM", precision = 15)
	public BigDecimal getLpcSumm() {
		return this.lpcSumm;
	}

	public void setLpcSumm(BigDecimal lpcSumm) {
		this.lpcSumm = lpcSumm;
	}

	@Column(name = "LPC_SUM_TRANSPORT", precision = 15)
	public BigDecimal getLpcSumTransport() {
		return this.lpcSumTransport;
	}

	public void setLpcSumTransport(BigDecimal lpcSumTransport) {
		this.lpcSumTransport = lpcSumTransport;
	}

	@Column(name = "LPC_CUSTOM", precision = 15)
	public BigDecimal getLpcCustom() {
		return this.lpcCustom;
	}

	public void setLpcCustom(BigDecimal lpcCustom) {
		this.lpcCustom = lpcCustom;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "dclPrcListProduce")
	public Set<DclShpListProduce> getDclShpListProduces() {
		return this.dclShpListProduces;
	}

	public void setDclShpListProduces(Set<DclShpListProduce> dclShpListProduces) {
		this.dclShpListProduces = dclShpListProduces;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PRD_ID")
	public DboProduce getProduce() {
		return produce;
	}

	public void setProduce(DboProduce produce) {
		this.produce = produce;
	}
}
