package net.sam.dcl.dbo.dirty;

// Generated 23-May-2007 22:53:40 by Hibernate Tools 3.2.0.b9

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DclProduceCostCustomId generated by hbm2java
 */
@Embeddable
public class DclProduceCostCustomId implements java.io.Serializable {

	private int prcId;

	private BigDecimal lpcPercent;

	private BigDecimal lpcSumm;

	private BigDecimal lpcSummAllocation;

	public DclProduceCostCustomId() {
	}

	public DclProduceCostCustomId(int prcId) {
		this.prcId = prcId;
	}

	public DclProduceCostCustomId(int prcId, BigDecimal lpcPercent,
			BigDecimal lpcSumm, BigDecimal lpcSummAllocation) {
		this.prcId = prcId;
		this.lpcPercent = lpcPercent;
		this.lpcSumm = lpcSumm;
		this.lpcSummAllocation = lpcSummAllocation;
	}

	@Column(name = "PRC_ID", nullable = false)
	public int getPrcId() {
		return this.prcId;
	}

	public void setPrcId(int prcId) {
		this.prcId = prcId;
	}

	@Column(name = "LPC_PERCENT", precision = 15)
	public BigDecimal getLpcPercent() {
		return this.lpcPercent;
	}

	public void setLpcPercent(BigDecimal lpcPercent) {
		this.lpcPercent = lpcPercent;
	}

	@Column(name = "LPC_SUMM", precision = 15)
	public BigDecimal getLpcSumm() {
		return this.lpcSumm;
	}

	public void setLpcSumm(BigDecimal lpcSumm) {
		this.lpcSumm = lpcSumm;
	}

	@Column(name = "LPC_SUMM_ALLOCATION", precision = 15)
	public BigDecimal getLpcSummAllocation() {
		return this.lpcSummAllocation;
	}

	public void setLpcSummAllocation(BigDecimal lpcSummAllocation) {
		this.lpcSummAllocation = lpcSummAllocation;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DclProduceCostCustomId))
			return false;
		DclProduceCostCustomId castOther = (DclProduceCostCustomId) other;

		return (this.getPrcId() == castOther.getPrcId())
				&& ((this.getLpcPercent() == castOther.getLpcPercent()) || (this
						.getLpcPercent() != null
						&& castOther.getLpcPercent() != null && this
						.getLpcPercent().equals(castOther.getLpcPercent())))
				&& ((this.getLpcSumm() == castOther.getLpcSumm()) || (this
						.getLpcSumm() != null
						&& castOther.getLpcSumm() != null && this.getLpcSumm()
						.equals(castOther.getLpcSumm())))
				&& ((this.getLpcSummAllocation() == castOther
						.getLpcSummAllocation()) || (this
						.getLpcSummAllocation() != null
						&& castOther.getLpcSummAllocation() != null && this
						.getLpcSummAllocation().equals(
								castOther.getLpcSummAllocation())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getPrcId();
		result = 37
				* result
				+ (getLpcPercent() == null ? 0 : this.getLpcPercent()
						.hashCode());
		result = 37 * result
				+ (getLpcSumm() == null ? 0 : this.getLpcSumm().hashCode());
		result = 37
				* result
				+ (getLpcSummAllocation() == null ? 0 : this
						.getLpcSummAllocation().hashCode());
		return result;
	}

}
