package net.sam.dcl.dbo.dirty;

// Generated 23-May-2007 22:53:40 by Hibernate Tools 3.2.0.b9

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * DclPayListSum generated by hbm2java
 */
@Entity
@Table(name = "DCL_PAY_LIST_SUMM")
public class DclPayListSum implements java.io.Serializable {

	private int lpsId;

	private DclConListSpec dclConListSpec;

	private DclPayment dclPayment;

	private BigDecimal lpsSumm;

	private BigDecimal lpsSummEur;

	private BigDecimal lpsSummOutNds;

	public DclPayListSum() {
	}

	public DclPayListSum(int lpsId, DclPayment dclPayment) {
		this.lpsId = lpsId;
		this.dclPayment = dclPayment;
	}

	public DclPayListSum(int lpsId, DclConListSpec dclConListSpec,
	                     DclPayment dclPayment, BigDecimal lpsSumm, BigDecimal lpsSummEur,
	                     BigDecimal lpsSummOutNds) {
		this.lpsId = lpsId;
		this.dclConListSpec = dclConListSpec;
		this.dclPayment = dclPayment;
		this.lpsSumm = lpsSumm;
		this.lpsSummEur = lpsSummEur;
		this.lpsSummOutNds = lpsSummOutNds;
	}

	@Id
	@Column(name = "LPS_ID", unique = true, nullable = false)
	public int getLpsId() {
		return this.lpsId;
	}

	public void setLpsId(int lpsId) {
		this.lpsId = lpsId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SPC_ID")
	public DclConListSpec getDclConListSpec() {
		return this.dclConListSpec;
	}

	public void setDclConListSpec(DclConListSpec dclConListSpec) {
		this.dclConListSpec = dclConListSpec;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PAY_ID", nullable = false)
	public DclPayment getDclPayment() {
		return this.dclPayment;
	}

	public void setDclPayment(DclPayment dclPayment) {
		this.dclPayment = dclPayment;
	}

	@Column(name = "LPS_SUMM", precision = 15)
	public BigDecimal getLpsSumm() {
		return this.lpsSumm;
	}

	public void setLpsSumm(BigDecimal lpsSumm) {
		this.lpsSumm = lpsSumm;
	}

	@Column(name = "LPS_SUMM_EUR", precision = 15)
	public BigDecimal getLpsSummEur() {
		return this.lpsSummEur;
	}

	public void setLpsSummEur(BigDecimal lpsSummEur) {
		this.lpsSummEur = lpsSummEur;
	}

	@Column(name = "LPS_SUMM_OUT_NDS", precision = 15)
	public BigDecimal getLpsSummOutNds() {
		return this.lpsSummOutNds;
	}

	public void setLpsSummOutNds(BigDecimal lpsSummOutNds) {
		this.lpsSummOutNds = lpsSummOutNds;
	}

}
