package net.sam.dcl.dbo.dirty;

// Generated 23-May-2007 22:53:40 by Hibernate Tools 3.2.0.b9

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * DclProduceCostCustom generated by hbm2java
 */
@Entity
@Table(name = "DCL_PRODUCE_COST_CUSTOM")
public class DclProduceCostCustom implements java.io.Serializable {

	private DclProduceCostCustomId id;

	public DclProduceCostCustom() {
	}

	public DclProduceCostCustom(DclProduceCostCustomId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides( {
			@AttributeOverride(name = "prcId", column = @Column(name = "PRC_ID", nullable = false)),
			@AttributeOverride(name = "lpcPercent", column = @Column(name = "LPC_PERCENT", precision = 15)),
			@AttributeOverride(name = "lpcSumm", column = @Column(name = "LPC_SUMM", precision = 15)),
			@AttributeOverride(name = "lpcSummAllocation", column = @Column(name = "LPC_SUMM_ALLOCATION", precision = 15)) })
	public DclProduceCostCustomId getId() {
		return this.id;
	}

	public void setId(DclProduceCostCustomId id) {
		this.id = id;
	}

}
