package net.sam.dcl.dbo.dirty;

// Generated 23-May-2007 22:53:40 by Hibernate Tools 3.2.0.b9

import net.sam.dcl.dbo.DboUser;

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DclPayment generated by hbm2java
 */
@Entity
@Table(name = "DCL_PAYMENT")
public class DclPayment implements java.io.Serializable {

	private int payId;

	private DclCurrency dclCurrency;

	private DclContractor dclContractor;

	private DboUser dclUserByUsrIdCreate;

	private DboUser dclUserByUsrIdEdit;

	private Date payCreateDate;

	private Date payEditDate;

	private Date payDate;

	private String payAccount;

	private BigDecimal paySum;

	private BigDecimal payCourse;

	private Short payBlock;

	private String payComment;

	private Set<DclPayListSum> dclPayListSums = new HashSet<DclPayListSum>(0);

	public DclPayment() {
	}

	public DclPayment(int payId, DclCurrency dclCurrency, BigDecimal paySum) {
		this.payId = payId;
		this.dclCurrency = dclCurrency;
		this.paySum = paySum;
	}

	public DclPayment(int payId, DclCurrency dclCurrency,
			DclContractor dclContractor, DboUser dclUserByUsrIdCreate,
			DboUser dclUserByUsrIdEdit, Date payCreateDate, Date payEditDate,
			Date payDate, String payAccount, BigDecimal paySum,
			BigDecimal payCourse, Short payBlock, String payComment,
			Set<DclPayListSum> dclPayListSums) {
		this.payId = payId;
		this.dclCurrency = dclCurrency;
		this.dclContractor = dclContractor;
		this.dclUserByUsrIdCreate = dclUserByUsrIdCreate;
		this.dclUserByUsrIdEdit = dclUserByUsrIdEdit;
		this.payCreateDate = payCreateDate;
		this.payEditDate = payEditDate;
		this.payDate = payDate;
		this.payAccount = payAccount;
		this.paySum = paySum;
		this.payCourse = payCourse;
		this.payBlock = payBlock;
		this.payComment = payComment;
		this.dclPayListSums = dclPayListSums;
	}

	@Id
	@Column(name = "PAY_ID", unique = true, nullable = false)
	public int getPayId() {
		return this.payId;
	}

	public void setPayId(int payId) {
		this.payId = payId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CUR_ID", nullable = false)
	public DclCurrency getDclCurrency() {
		return this.dclCurrency;
	}

	public void setDclCurrency(DclCurrency dclCurrency) {
		this.dclCurrency = dclCurrency;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CTR_ID")
	public DclContractor getDclContractor() {
		return this.dclContractor;
	}

	public void setDclContractor(DclContractor dclContractor) {
		this.dclContractor = dclContractor;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "USR_ID_CREATE")
	public DboUser getDclUserByUsrIdCreate() {
		return this.dclUserByUsrIdCreate;
	}

	public void setDclUserByUsrIdCreate(DboUser dclUserByUsrIdCreate) {
		this.dclUserByUsrIdCreate = dclUserByUsrIdCreate;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "USR_ID_EDIT")
	public DboUser getDclUserByUsrIdEdit() {
		return this.dclUserByUsrIdEdit;
	}

	public void setDclUserByUsrIdEdit(DboUser dclUserByUsrIdEdit) {
		this.dclUserByUsrIdEdit = dclUserByUsrIdEdit;
	}

	@Column(name = "PAY_CREATE_DATE", length = 19)
	public Date getPayCreateDate() {
		return this.payCreateDate;
	}

	public void setPayCreateDate(Date payCreateDate) {
		this.payCreateDate = payCreateDate;
	}

	@Column(name = "PAY_EDIT_DATE", length = 19)
	public Date getPayEditDate() {
		return this.payEditDate;
	}

	public void setPayEditDate(Date payEditDate) {
		this.payEditDate = payEditDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "PAY_DATE", length = 10)
	public Date getPayDate() {
		return this.payDate;
	}

	public void setPayDate(Date payDate) {
		this.payDate = payDate;
	}

	@Column(name = "PAY_ACCOUNT", length = 35)
	public String getPayAccount() {
		return this.payAccount;
	}

	public void setPayAccount(String payAccount) {
		this.payAccount = payAccount;
	}

	@Column(name = "PAY_SUMM", nullable = false, precision = 15)
	public BigDecimal getPaySum() {
		return this.paySum;
	}

	public void setPaySum(BigDecimal paySum) {
		this.paySum = paySum;
	}

	@Column(name = "PAY_COURSE", precision = 15, scale = 4)
	public BigDecimal getPayCourse() {
		return this.payCourse;
	}

	public void setPayCourse(BigDecimal payCourse) {
		this.payCourse = payCourse;
	}

	@Column(name = "PAY_BLOCK")
	public Short getPayBlock() {
		return this.payBlock;
	}

	public void setPayBlock(Short payBlock) {
		this.payBlock = payBlock;
	}

	@Column(name = "PAY_COMMENT", length = 200)
	public String getPayComment() {
		return this.payComment;
	}

	public void setPayComment(String payComment) {
		this.payComment = payComment;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "dclPayment")
	public Set<DclPayListSum> getDclPayListSums() {
		return this.dclPayListSums;
	}

	public void setDclPayListSums(Set<DclPayListSum> dclPayListSums) {
		this.dclPayListSums = dclPayListSums;
	}

}
