package net.sam.dcl.dbo.dirty;

// Generated 23-May-2007 22:53:40 by Hibernate Tools 3.2.0.b9

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DclRestProduceCostProduceVId generated by hbm2java
 */
@Embeddable
public class DclRestProduceCostProduceVId implements java.io.Serializable {

	private Integer lpcId;

	private Integer prcId;

	private String prcNumber;

	private Date prcDate;

	private String lpcProduceName;

	private Integer stfId;

	private String stfName;

	private Integer rutId;

	private BigDecimal lpcCount;

	private BigDecimal freeCount;

	public DclRestProduceCostProduceVId() {
	}

	public DclRestProduceCostProduceVId(Integer lpcId, Integer prcId,
			String prcNumber, Date prcDate, String lpcProduceName,
			Integer stfId, String stfName, Integer rutId, BigDecimal lpcCount,
			BigDecimal freeCount) {
		this.lpcId = lpcId;
		this.prcId = prcId;
		this.prcNumber = prcNumber;
		this.prcDate = prcDate;
		this.lpcProduceName = lpcProduceName;
		this.stfId = stfId;
		this.stfName = stfName;
		this.rutId = rutId;
		this.lpcCount = lpcCount;
		this.freeCount = freeCount;
	}

	@Column(name = "LPC_ID")
	public Integer getLpcId() {
		return this.lpcId;
	}

	public void setLpcId(Integer lpcId) {
		this.lpcId = lpcId;
	}

	@Column(name = "PRC_ID")
	public Integer getPrcId() {
		return this.prcId;
	}

	public void setPrcId(Integer prcId) {
		this.prcId = prcId;
	}

	@Column(name = "PRC_NUMBER", length = 50)
	public String getPrcNumber() {
		return this.prcNumber;
	}

	public void setPrcNumber(String prcNumber) {
		this.prcNumber = prcNumber;
	}

	@Column(name = "PRC_DATE", length = 10)
	public Date getPrcDate() {
		return this.prcDate;
	}

	public void setPrcDate(Date prcDate) {
		this.prcDate = prcDate;
	}

	@Column(name = "LPC_PRODUCE_NAME", length = 1000)
	public String getLpcProduceName() {
		return this.lpcProduceName;
	}

	public void setLpcProduceName(String lpcProduceName) {
		this.lpcProduceName = lpcProduceName;
	}

	@Column(name = "STF_ID")
	public Integer getStfId() {
		return this.stfId;
	}

	public void setStfId(Integer stfId) {
		this.stfId = stfId;
	}

	@Column(name = "STF_NAME", length = 0)
	public String getStfName() {
		return this.stfName;
	}

	public void setStfName(String stfName) {
		this.stfName = stfName;
	}

	@Column(name = "RUT_ID")
	public Integer getRutId() {
		return this.rutId;
	}

	public void setRutId(Integer rutId) {
		this.rutId = rutId;
	}

	@Column(name = "LPC_COUNT", precision = 15)
	public BigDecimal getLpcCount() {
		return this.lpcCount;
	}

	public void setLpcCount(BigDecimal lpcCount) {
		this.lpcCount = lpcCount;
	}

	@Column(name = "FREE_COUNT", precision = 0)
	public BigDecimal getFreeCount() {
		return this.freeCount;
	}

	public void setFreeCount(BigDecimal freeCount) {
		this.freeCount = freeCount;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DclRestProduceCostProduceVId))
			return false;
		DclRestProduceCostProduceVId castOther = (DclRestProduceCostProduceVId) other;

		return ((this.getLpcId() == castOther.getLpcId()) || (this.getLpcId() != null
				&& castOther.getLpcId() != null && this.getLpcId().equals(
				castOther.getLpcId())))
				&& ((this.getPrcId() == castOther.getPrcId()) || (this
						.getPrcId() != null
						&& castOther.getPrcId() != null && this.getPrcId()
						.equals(castOther.getPrcId())))
				&& ((this.getPrcNumber() == castOther.getPrcNumber()) || (this
						.getPrcNumber() != null
						&& castOther.getPrcNumber() != null && this
						.getPrcNumber().equals(castOther.getPrcNumber())))
				&& ((this.getPrcDate() == castOther.getPrcDate()) || (this
						.getPrcDate() != null
						&& castOther.getPrcDate() != null && this.getPrcDate()
						.equals(castOther.getPrcDate())))
				&& ((this.getLpcProduceName() == castOther.getLpcProduceName()) || (this
						.getLpcProduceName() != null
						&& castOther.getLpcProduceName() != null && this
						.getLpcProduceName().equals(
								castOther.getLpcProduceName())))
				&& ((this.getStfId() == castOther.getStfId()) || (this
						.getStfId() != null
						&& castOther.getStfId() != null && this.getStfId()
						.equals(castOther.getStfId())))
				&& ((this.getStfName() == castOther.getStfName()) || (this
						.getStfName() != null
						&& castOther.getStfName() != null && this.getStfName()
						.equals(castOther.getStfName())))
				&& ((this.getRutId() == castOther.getRutId()) || (this
						.getRutId() != null
						&& castOther.getRutId() != null && this.getRutId()
						.equals(castOther.getRutId())))
				&& ((this.getLpcCount() == castOther.getLpcCount()) || (this
						.getLpcCount() != null
						&& castOther.getLpcCount() != null && this
						.getLpcCount().equals(castOther.getLpcCount())))
				&& ((this.getFreeCount() == castOther.getFreeCount()) || (this
						.getFreeCount() != null
						&& castOther.getFreeCount() != null && this
						.getFreeCount().equals(castOther.getFreeCount())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getLpcId() == null ? 0 : this.getLpcId().hashCode());
		result = 37 * result
				+ (getPrcId() == null ? 0 : this.getPrcId().hashCode());
		result = 37 * result
				+ (getPrcNumber() == null ? 0 : this.getPrcNumber().hashCode());
		result = 37 * result
				+ (getPrcDate() == null ? 0 : this.getPrcDate().hashCode());
		result = 37
				* result
				+ (getLpcProduceName() == null ? 0 : this.getLpcProduceName()
						.hashCode());
		result = 37 * result
				+ (getStfId() == null ? 0 : this.getStfId().hashCode());
		result = 37 * result
				+ (getStfName() == null ? 0 : this.getStfName().hashCode());
		result = 37 * result
				+ (getRutId() == null ? 0 : this.getRutId().hashCode());
		result = 37 * result
				+ (getLpcCount() == null ? 0 : this.getLpcCount().hashCode());
		result = 37 * result
				+ (getFreeCount() == null ? 0 : this.getFreeCount().hashCode());
		return result;
	}

}
