package net.sam.dcl.dbo.dirty;

// Generated 23-May-2007 22:53:40 by Hibernate Tools 3.2.0.b9

import net.sam.dcl.dbo.DboUser;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * DclRole generated by hbm2java
 */
@Entity
@Table(name = "DCL_ROLE")
public class DclRole implements java.io.Serializable {

	private int rolId;

	private String rolName;

	private Set<DboUser> dclUsers = new HashSet<DboUser>(0);

	public DclRole() {
	}

	public DclRole(int rolId, String rolName) {
		this.rolId = rolId;
		this.rolName = rolName;
	}

	public DclRole(int rolId, String rolName, Set<DboUser> dclUsers) {
		this.rolId = rolId;
		this.rolName = rolName;
		this.dclUsers = dclUsers;
	}

	@Id
	@Column(name = "ROL_ID", unique = true, nullable = false)
	public int getRolId() {
		return this.rolId;
	}

	public void setRolId(int rolId) {
		this.rolId = rolId;
	}

	@Column(name = "ROL_NAME", nullable = false, length = 32)
	public String getRolName() {
		return this.rolName;
	}

	public void setRolName(String rolName) {
		this.rolName = rolName;
	}

	@ManyToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "roles")
	public Set<DboUser> getDclUsers() {
		return this.dclUsers;
	}

	public void setDclUsers(Set<DboUser> dclUsers) {
		this.dclUsers = dclUsers;
	}

}
