package net.sam.dcl.dbo.dirty;

// Generated 23-May-2007 22:53:40 by Hibernate Tools 3.2.0.b9

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * DclRestProduceCostProduceV generated by hbm2java
 */
@Entity
@Table(name = "DCL_REST_PRODUCE_COST_PRODUCE_V")
public class DclRestProduceCostProduceV implements java.io.Serializable {

	private DclRestProduceCostProduceVId id;

	public DclRestProduceCostProduceV() {
	}

	public DclRestProduceCostProduceV(DclRestProduceCostProduceVId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides( {
			@AttributeOverride(name = "lpcId", column = @Column(name = "LPC_ID")),
			@AttributeOverride(name = "prcId", column = @Column(name = "PRC_ID")),
			@AttributeOverride(name = "prcNumber", column = @Column(name = "PRC_NUMBER", length = 50)),
			@AttributeOverride(name = "prcDate", column = @Column(name = "PRC_DATE", length = 10)),
			@AttributeOverride(name = "lpcProduceName", column = @Column(name = "LPC_PRODUCE_NAME", length = 1000)),
			@AttributeOverride(name = "stfId", column = @Column(name = "STF_ID")),
			@AttributeOverride(name = "stfName", column = @Column(name = "STF_NAME", length = 0)),
			@AttributeOverride(name = "rutId", column = @Column(name = "RUT_ID")),
			@AttributeOverride(name = "lpcCount", column = @Column(name = "LPC_COUNT", precision = 15)),
			@AttributeOverride(name = "freeCount", column = @Column(name = "FREE_COUNT", precision = 0)) })
	public DclRestProduceCostProduceVId getId() {
		return this.id;
	}

	public void setId(DclRestProduceCostProduceVId id) {
		this.id = id;
	}

}
