package net.sam.dcl.dbo.dirty;

// Generated 23-May-2007 22:53:40 by Hibernate Tools 3.2.0.b9

import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * DclRoute generated by hbm2java
 */
@Entity
@Table(name = "DCL_ROUTE")
public class DclRoute implements java.io.Serializable {

	private int rutId;

	private String rutName;

	public DclRoute() {
	}

	public DclRoute(int rutId) {
		this.rutId = rutId;
	}

	public DclRoute(int rutId, String rutName) {
		this.rutId = rutId;
		this.rutName = rutName;
	}

	@Id
	@Column(name = "RUT_ID", unique = true, nullable = false)
	public int getRutId() {
		return this.rutId;
	}

	public void setRutId(int rutId) {
		this.rutId = rutId;
	}

	@Column(name = "RUT_NAME", length = 150)
	public String getRutName() {
		return this.rutName;
	}

	public void setRutName(String rutName) {
		this.rutName = rutName;
	}
}
