package net.sam.dcl.dbo.dirty;

// Generated 23-May-2007 22:53:40 by Hibernate Tools 3.2.0.b9

import net.sam.dcl.dbo.DboUser;

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DclShipping generated by hbm2java
 */
@Entity
@Table(name = "DCL_SHIPPING")
public class DclShipping implements java.io.Serializable {

	private int shpId;

	private DclCurrency dclCurrency;

	private DclContractor dclContractor;

	private DboUser dclUserByUsrIdCreate;

	private DclConListSpec dclConListSpec;

	private DboUser dclUserByUsrIdEdit;

	private Date shpCreateDate;

	private Date shpEditDate;

	private String shpNumber;

	private Date shpDate;

	private BigDecimal shpSummPlusNds;

	private Short shpBlock;

	private Set<DclShpListProduce> dclShpListProduces = new HashSet<DclShpListProduce>(
			0);

	public DclShipping() {
	}

	public DclShipping(int shpId, DclCurrency dclCurrency,
			DclContractor dclContractor, String shpNumber,
			BigDecimal shpSummPlusNds) {
		this.shpId = shpId;
		this.dclCurrency = dclCurrency;
		this.dclContractor = dclContractor;
		this.shpNumber = shpNumber;
		this.shpSummPlusNds = shpSummPlusNds;
	}

	public DclShipping(int shpId, DclCurrency dclCurrency,
			DclContractor dclContractor, DboUser dclUserByUsrIdCreate,
			DclConListSpec dclConListSpec, DboUser dclUserByUsrIdEdit,
			Date shpCreateDate, Date shpEditDate, String shpNumber,
			Date shpDate, BigDecimal shpSummPlusNds, Short shpBlock,
			Set<DclShpListProduce> dclShpListProduces) {
		this.shpId = shpId;
		this.dclCurrency = dclCurrency;
		this.dclContractor = dclContractor;
		this.dclUserByUsrIdCreate = dclUserByUsrIdCreate;
		this.dclConListSpec = dclConListSpec;
		this.dclUserByUsrIdEdit = dclUserByUsrIdEdit;
		this.shpCreateDate = shpCreateDate;
		this.shpEditDate = shpEditDate;
		this.shpNumber = shpNumber;
		this.shpDate = shpDate;
		this.shpSummPlusNds = shpSummPlusNds;
		this.shpBlock = shpBlock;
		this.dclShpListProduces = dclShpListProduces;
	}

	@Id
	@Column(name = "SHP_ID", unique = true, nullable = false)
	public int getShpId() {
		return this.shpId;
	}

	public void setShpId(int shpId) {
		this.shpId = shpId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CUR_ID", nullable = false)
	public DclCurrency getDclCurrency() {
		return this.dclCurrency;
	}

	public void setDclCurrency(DclCurrency dclCurrency) {
		this.dclCurrency = dclCurrency;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CTR_ID", nullable = false)
	public DclContractor getDclContractor() {
		return this.dclContractor;
	}

	public void setDclContractor(DclContractor dclContractor) {
		this.dclContractor = dclContractor;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "USR_ID_CREATE")
	public DboUser getDclUserByUsrIdCreate() {
		return this.dclUserByUsrIdCreate;
	}

	public void setDclUserByUsrIdCreate(DboUser dclUserByUsrIdCreate) {
		this.dclUserByUsrIdCreate = dclUserByUsrIdCreate;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SPC_ID")
	public DclConListSpec getDclConListSpec() {
		return this.dclConListSpec;
	}

	public void setDclConListSpec(DclConListSpec dclConListSpec) {
		this.dclConListSpec = dclConListSpec;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "USR_ID_EDIT")
	public DboUser getDclUserByUsrIdEdit() {
		return this.dclUserByUsrIdEdit;
	}

	public void setDclUserByUsrIdEdit(DboUser dclUserByUsrIdEdit) {
		this.dclUserByUsrIdEdit = dclUserByUsrIdEdit;
	}

	@Column(name = "SHP_CREATE_DATE", length = 19)
	public Date getShpCreateDate() {
		return this.shpCreateDate;
	}

	public void setShpCreateDate(Date shpCreateDate) {
		this.shpCreateDate = shpCreateDate;
	}

	@Column(name = "SHP_EDIT_DATE", length = 19)
	public Date getShpEditDate() {
		return this.shpEditDate;
	}

	public void setShpEditDate(Date shpEditDate) {
		this.shpEditDate = shpEditDate;
	}

	@Column(name = "SHP_NUMBER", nullable = false, length = 50)
	public String getShpNumber() {
		return this.shpNumber;
	}

	public void setShpNumber(String shpNumber) {
		this.shpNumber = shpNumber;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "SHP_DATE", length = 10)
	public Date getShpDate() {
		return this.shpDate;
	}

	public void setShpDate(Date shpDate) {
		this.shpDate = shpDate;
	}

	@Column(name = "SHP_SUMM_PLUS_NDS", nullable = false, precision = 15)
	public BigDecimal getShpSummPlusNds() {
		return this.shpSummPlusNds;
	}

	public void setShpSummPlusNds(BigDecimal shpSummPlusNds) {
		this.shpSummPlusNds = shpSummPlusNds;
	}

	@Column(name = "SHP_BLOCK")
	public Short getShpBlock() {
		return this.shpBlock;
	}

	public void setShpBlock(Short shpBlock) {
		this.shpBlock = shpBlock;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "dclShipping")
	public Set<DclShpListProduce> getDclShpListProduces() {
		return this.dclShpListProduces;
	}

	public void setDclShpListProduces(Set<DclShpListProduce> dclShpListProduces) {
		this.dclShpListProduces = dclShpListProduces;
	}

}
