package net.sam.dcl.dbo.dirty;

// Generated 28-Oct-2007 16:33:48 by Hibernate Tools 3.2.0.b9

import net.sam.dcl.dbo.DboProduce;


import javax.persistence.*;
import java.math.BigDecimal;

/**
 * DclSpiListProduce generated by hbm2java
 */
@Entity
@Table(name = "DCL_SPI_LIST_PRODUCE")
public class DclSpiListProduce implements java.io.Serializable {

	private int sipId;
	private DclSpecificationImport dclSpecificationImport;
	private DboProduce produce;
	private DclDlrListProduce dclDlrListProduce;
	private BigDecimal sipPrice;
	private BigDecimal sipCount;
	private BigDecimal sipCost;
	private BigDecimal sipWeight;

	public DclSpiListProduce() {
	}

	public DclSpiListProduce(int sipId,
			DclSpecificationImport dclSpecificationImport,
			DboProduce dclProduce, BigDecimal sipPrice, BigDecimal sipCount,
			BigDecimal sipCost) {
		this.sipId = sipId;
		this.dclSpecificationImport = dclSpecificationImport;
		this.produce = dclProduce;
		this.sipPrice = sipPrice;
		this.sipCount = sipCount;
		this.sipCost = sipCost;
	}

	public DclSpiListProduce(int sipId,
			DclSpecificationImport dclSpecificationImport,
			DboProduce dclProduce, DclDlrListProduce dclDlrListProduce,
			BigDecimal sipPrice, BigDecimal sipCount, BigDecimal sipCost,
			BigDecimal sipWeight) {
		this.sipId = sipId;
		this.dclSpecificationImport = dclSpecificationImport;
		this.produce = dclProduce;
		this.dclDlrListProduce = dclDlrListProduce;
		this.sipPrice = sipPrice;
		this.sipCount = sipCount;
		this.sipCost = sipCost;
		this.sipWeight = sipWeight;
	}

	@Id
	@Column(name = "SIP_ID", unique = true, nullable = false)
	public int getSipId() {
		return this.sipId;
	}

	public void setSipId(int sipId) {
		this.sipId = sipId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SPI_ID", nullable = false)
	public DclSpecificationImport getDclSpecificationImport() {
		return this.dclSpecificationImport;
	}

	public void setDclSpecificationImport(
			DclSpecificationImport dclSpecificationImport) {
		this.dclSpecificationImport = dclSpecificationImport;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PRD_ID", nullable = false)
	public DboProduce getProduce() {
		return this.produce;
	}

	public void setProduce(DboProduce pProduce) {
		this.produce = pProduce;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DRP_ID")
	public DclDlrListProduce getDclDlrListProduce() {
		return this.dclDlrListProduce;
	}

	public void setDclDlrListProduce(DclDlrListProduce dclDlrListProduce) {
		this.dclDlrListProduce = dclDlrListProduce;
	}

	@Column(name = "SIP_PRICE", nullable = false, precision = 15)
	public BigDecimal getSipPrice() {
		return this.sipPrice;
	}

	public void setSipPrice(BigDecimal sipPrice) {
		this.sipPrice = sipPrice;
	}

	@Column(name = "SIP_COUNT", nullable = false, precision = 15)
	public BigDecimal getSipCount() {
		return this.sipCount;
	}

	public void setSipCount(BigDecimal sipCount) {
		this.sipCount = sipCount;
	}

	@Column(name = "SIP_COST", nullable = false, precision = 15)
	public BigDecimal getSipCost() {
		return this.sipCost;
	}

	public void setSipCost(BigDecimal sipCost) {
		this.sipCost = sipCost;
	}

	@Column(name = "SIP_WEIGHT", precision = 15, scale = 3)
	public BigDecimal getSipWeight() {
		return this.sipWeight;
	}

	public void setSipWeight(BigDecimal sipWeight) {
		this.sipWeight = sipWeight;
	}

}
