package net.sam.dcl.dbo.dirty;

// Generated 23-May-2007 22:53:40 by Hibernate Tools 3.2.0.b9

import net.sam.dcl.dbo.DboStuffCategory;
import net.sam.dcl.dbo.DboUser;

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * DclShpListProduce generated by hbm2java
 */
@Entity
@Table(name = "DCL_SHP_LIST_PRODUCE")
public class DclShpListProduce implements java.io.Serializable {

	private int lpsId;

	private DboUser dclUser;

	private DboStuffCategory dboStuffCategory;

	private DclPrcListProduce dclPrcListProduce;

	private DclShipping dclShipping;

	private BigDecimal lpsCount;

	private BigDecimal lpsSummPlusNds;

	public DclShpListProduce() {
	}

	public DclShpListProduce(int lpsId, DclPrcListProduce dclPrcListProduce,
			DclShipping dclShipping) {
		this.lpsId = lpsId;
		this.dclPrcListProduce = dclPrcListProduce;
		this.dclShipping = dclShipping;
	}

	public DclShpListProduce(int lpsId, DboUser dclUser,
			DboStuffCategory dboStuffCategory,
			DclPrcListProduce dclPrcListProduce, DclShipping dclShipping,
			BigDecimal lpsCount, BigDecimal lpsSummPlusNds,
			BigDecimal lpsSumTransport, BigDecimal lpsCustom,
			BigDecimal lpsSummZak) {
		this.lpsId = lpsId;
		this.dclUser = dclUser;
		this.dboStuffCategory = dboStuffCategory;
		this.dclPrcListProduce = dclPrcListProduce;
		this.dclShipping = dclShipping;
		this.lpsCount = lpsCount;
		this.lpsSummPlusNds = lpsSummPlusNds;
	}

	@Id
	@Column(name = "LPS_ID", unique = true, nullable = false)
	public int getLpsId() {
		return this.lpsId;
	}

	public void setLpsId(int lpsId) {
		this.lpsId = lpsId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "USR_ID")
	public DboUser getDclUser() {
		return this.dclUser;
	}

	public void setDclUser(DboUser dclUser) {
		this.dclUser = dclUser;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "STF_ID")
	public DboStuffCategory getDclStuffCategory() {
		return this.dboStuffCategory;
	}

	public void setDclStuffCategory(DboStuffCategory dboStuffCategory) {
		this.dboStuffCategory = dboStuffCategory;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "LPC_ID", nullable = false)
	public DclPrcListProduce getDclPrcListProduce() {
		return this.dclPrcListProduce;
	}

	public void setDclPrcListProduce(DclPrcListProduce dclPrcListProduce) {
		this.dclPrcListProduce = dclPrcListProduce;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SHP_ID", nullable = false)
	public DclShipping getDclShipping() {
		return this.dclShipping;
	}

	public void setDclShipping(DclShipping dclShipping) {
		this.dclShipping = dclShipping;
	}

	@Column(name = "LPS_COUNT", precision = 15)
	public BigDecimal getLpsCount() {
		return this.lpsCount;
	}

	public void setLpsCount(BigDecimal lpsCount) {
		this.lpsCount = lpsCount;
	}

	@Column(name = "LPS_SUMM_PLUS_NDS", precision = 15)
	public BigDecimal getLpsSummPlusNds() {
		return this.lpsSummPlusNds;
	}

	public void setLpsSummPlusNds(BigDecimal lpsSummPlusNds) {
		this.lpsSummPlusNds = lpsSummPlusNds;
	}

}
