package net.sam.dcl.dbo.dirty;

// Generated 28-Oct-2007 16:33:48 by Hibernate Tools 3.2.0.b9


import net.sam.dcl.dbo.dirty.DclSpiListProduce;
import net.sam.dcl.dbo.DboUser;

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DclSpecificationImport generated by hbm2java
 */
@Entity
@Table(name = "DCL_SPECIFICATION_IMPORT")
public class DclSpecificationImport implements java.io.Serializable {

	private int spiId;
	private DboUser dclUserByUsrIdCreate;
	private DboUser dclUserByUsrIdEdit;
	private Date spiCreateDate;
	private Date spiEditDate;
	private String spiNumber;
	private Date spiDate;
	private String spiComment;
	private BigDecimal spiCourse;
	private BigDecimal spiKoeff;
	private Short spiArrive;
	private Set<DclSpiListProduce> dclSpiListProduces = new HashSet<DclSpiListProduce>(
			0);

	public DclSpecificationImport() {
	}

	public DclSpecificationImport(int spiId, DboUser dclUserByUsrIdCreate,
			DboUser dclUserByUsrIdEdit, Date spiCreateDate, Date spiEditDate,
			String spiNumber, Date spiDate) {
		this.spiId = spiId;
		this.dclUserByUsrIdCreate = dclUserByUsrIdCreate;
		this.dclUserByUsrIdEdit = dclUserByUsrIdEdit;
		this.spiCreateDate = spiCreateDate;
		this.spiEditDate = spiEditDate;
		this.spiNumber = spiNumber;
		this.spiDate = spiDate;
	}

	public DclSpecificationImport(int spiId, DboUser dclUserByUsrIdCreate,
			DboUser dclUserByUsrIdEdit, Date spiCreateDate, Date spiEditDate,
			String spiNumber, Date spiDate, String spiComment,
			BigDecimal spiCourse, BigDecimal spiKoeff, Short spiArrive,
			Set<DclSpiListProduce> dclSpiListProduces) {
		this.spiId = spiId;
		this.dclUserByUsrIdCreate = dclUserByUsrIdCreate;
		this.dclUserByUsrIdEdit = dclUserByUsrIdEdit;
		this.spiCreateDate = spiCreateDate;
		this.spiEditDate = spiEditDate;
		this.spiNumber = spiNumber;
		this.spiDate = spiDate;
		this.spiComment = spiComment;
		this.spiCourse = spiCourse;
		this.spiKoeff = spiKoeff;
		this.spiArrive = spiArrive;
		this.dclSpiListProduces = dclSpiListProduces;
	}

	@Id
	@Column(name = "SPI_ID", unique = true, nullable = false)
	public int getSpiId() {
		return this.spiId;
	}

	public void setSpiId(int spiId) {
		this.spiId = spiId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "USR_ID_CREATE", nullable = false)
	public DboUser getDclUserByUsrIdCreate() {
		return this.dclUserByUsrIdCreate;
	}

	public void setDclUserByUsrIdCreate(DboUser dclUserByUsrIdCreate) {
		this.dclUserByUsrIdCreate = dclUserByUsrIdCreate;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "USR_ID_EDIT", nullable = false)
	public DboUser getDclUserByUsrIdEdit() {
		return this.dclUserByUsrIdEdit;
	}

	public void setDclUserByUsrIdEdit(DboUser dclUserByUsrIdEdit) {
		this.dclUserByUsrIdEdit = dclUserByUsrIdEdit;
	}

	@Column(name = "SPI_CREATE_DATE", nullable = false, length = 19)
	public Date getSpiCreateDate() {
		return this.spiCreateDate;
	}

	public void setSpiCreateDate(Date spiCreateDate) {
		this.spiCreateDate = spiCreateDate;
	}

	@Column(name = "SPI_EDIT_DATE", nullable = false, length = 19)
	public Date getSpiEditDate() {
		return this.spiEditDate;
	}

	public void setSpiEditDate(Date spiEditDate) {
		this.spiEditDate = spiEditDate;
	}

	@Column(name = "SPI_NUMBER", nullable = false, length = 100)
	public String getSpiNumber() {
		return this.spiNumber;
	}

	public void setSpiNumber(String spiNumber) {
		this.spiNumber = spiNumber;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "SPI_DATE", nullable = false, length = 10)
	public Date getSpiDate() {
		return this.spiDate;
	}

	public void setSpiDate(Date spiDate) {
		this.spiDate = spiDate;
	}

	@Column(name = "SPI_COMMENT", length = 2000)
	public String getSpiComment() {
		return this.spiComment;
	}

	public void setSpiComment(String spiComment) {
		this.spiComment = spiComment;
	}

	@Column(name = "SPI_COURSE", precision = 15, scale = 6)
	public BigDecimal getSpiCourse() {
		return this.spiCourse;
	}

	public void setSpiCourse(BigDecimal spiCourse) {
		this.spiCourse = spiCourse;
	}

	@Column(name = "SPI_KOEFF", precision = 15, scale = 3)
	public BigDecimal getSpiKoeff() {
		return this.spiKoeff;
	}

	public void setSpiKoeff(BigDecimal spiKoeff) {
		this.spiKoeff = spiKoeff;
	}

	@Column(name = "SPI_ARRIVE")
	public Short getSpiArrive() {
		return this.spiArrive;
	}

	public void setSpiArrive(Short spiArrive) {
		this.spiArrive = spiArrive;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "dclSpecificationImport")
	public Set<DclSpiListProduce> getDclSpiListProduces() {
		return this.dclSpiListProduces;
	}

	public void setDclSpiListProduces(Set<DclSpiListProduce> dclSpiListProduces) {
		this.dclSpiListProduces = dclSpiListProduces;
	}

}
