package net.sam.dcl.dbo.dirty;

// Generated 23-May-2007 22:53:40 by Hibernate Tools 3.2.0.b9

import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * DclTermInco generated by hbm2java
 */
@Entity
@Table(name = "DCL_TERM_INCO")
public class DclTermInco implements java.io.Serializable {

	private int trmId;

	private String trmName;

	private Set<DclCommercialProposal> dclCommercialProposalsForTrmIdPriceCondition = new HashSet<DclCommercialProposal>(
			0);

	private Set<DclCommercialProposal> dclCommercialProposalsForTrmIdDeliveryCondition = new HashSet<DclCommercialProposal>(
			0);

	public DclTermInco() {
	}

	public DclTermInco(int trmId, String trmName) {
		this.trmId = trmId;
		this.trmName = trmName;
	}

	public DclTermInco(
			int trmId,
			String trmName,
			Set<DclCommercialProposal> dclCommercialProposalsForTrmIdPriceCondition,
			Set<DclCommercialProposal> dclCommercialProposalsForTrmIdDeliveryCondition) {
		this.trmId = trmId;
		this.trmName = trmName;
		this.dclCommercialProposalsForTrmIdPriceCondition = dclCommercialProposalsForTrmIdPriceCondition;
		this.dclCommercialProposalsForTrmIdDeliveryCondition = dclCommercialProposalsForTrmIdDeliveryCondition;
	}

	@Id
	@Column(name = "TRM_ID", unique = true, nullable = false)
	public int getTrmId() {
		return this.trmId;
	}

	public void setTrmId(int trmId) {
		this.trmId = trmId;
	}

	@Column(name = "TRM_NAME", nullable = false, length = 10)
	public String getTrmName() {
		return this.trmName;
	}

	public void setTrmName(String trmName) {
		this.trmName = trmName;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "dclTermIncoByTrmIdPriceCondition")
	public Set<DclCommercialProposal> getDclCommercialProposalsForTrmIdPriceCondition() {
		return this.dclCommercialProposalsForTrmIdPriceCondition;
	}

	public void setDclCommercialProposalsForTrmIdPriceCondition(
			Set<DclCommercialProposal> dclCommercialProposalsForTrmIdPriceCondition) {
		this.dclCommercialProposalsForTrmIdPriceCondition = dclCommercialProposalsForTrmIdPriceCondition;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "dclTermIncoByTrmIdDeliveryCondition")
	public Set<DclCommercialProposal> getDclCommercialProposalsForTrmIdDeliveryCondition() {
		return this.dclCommercialProposalsForTrmIdDeliveryCondition;
	}

	public void setDclCommercialProposalsForTrmIdDeliveryCondition(
			Set<DclCommercialProposal> dclCommercialProposalsForTrmIdDeliveryCondition) {
		this.dclCommercialProposalsForTrmIdDeliveryCondition = dclCommercialProposalsForTrmIdDeliveryCondition;
	}

}
