package net.sam.dcl.dbo.dirty;

// Generated 23-May-2007 22:53:40 by Hibernate Tools 3.2.0.b9

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * DclTest generated by hbm2java
 */
@Entity
@Table(name = "DCL_TEST")
public class DclTest implements java.io.Serializable {

	private int tstId;

	private String tstName;

	private BigDecimal tstDecimal;

	public DclTest() {
	}

	public DclTest(int tstId, String tstName) {
		this.tstId = tstId;
		this.tstName = tstName;
	}

	public DclTest(int tstId, String tstName, BigDecimal tstDecimal) {
		this.tstId = tstId;
		this.tstName = tstName;
		this.tstDecimal = tstDecimal;
	}

	@Id
	@Column(name = "TST_ID", unique = true, nullable = false)
	public int getTstId() {
		return this.tstId;
	}

	public void setTstId(int tstId) {
		this.tstId = tstId;
	}

	@Column(name = "TST_NAME", nullable = false, length = 128)
	public String getTstName() {
		return this.tstName;
	}

	public void setTstName(String tstName) {
		this.tstName = tstName;
	}

	@Column(name = "TST_DECIMAL", precision = 15)
	public BigDecimal getTstDecimal() {
		return this.tstDecimal;
	}

	public void setTstDecimal(BigDecimal tstDecimal) {
		this.tstDecimal = tstDecimal;
	}

}
