package net.sam.dcl.dbo.dirty;

// Generated 23-May-2007 22:53:40 by Hibernate Tools 3.2.0.b9

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DclUnclosedSpecVId generated by hbm2java
 */
@Embeddable
public class DclUnclosedSpecVId implements java.io.Serializable {

	private Integer ctrId;

	private String ctrName;

	private Integer conId;

	private String conNumber;

	private Date conDate;

	private Integer spcId;

	private String spcNumber;

	private Date spcDate;

	private BigDecimal spcSumm;

	public DclUnclosedSpecVId() {
	}

	public DclUnclosedSpecVId(Integer ctrId, String ctrName, Integer conId,
			String conNumber, Date conDate, Integer spcId, String spcNumber,
			Date spcDate, BigDecimal spcSumm) {
		this.ctrId = ctrId;
		this.ctrName = ctrName;
		this.conId = conId;
		this.conNumber = conNumber;
		this.conDate = conDate;
		this.spcId = spcId;
		this.spcNumber = spcNumber;
		this.spcDate = spcDate;
		this.spcSumm = spcSumm;
	}

	@Column(name = "CTR_ID")
	public Integer getCtrId() {
		return this.ctrId;
	}

	public void setCtrId(Integer ctrId) {
		this.ctrId = ctrId;
	}

	@Column(name = "CTR_NAME", length = 50)
	public String getCtrName() {
		return this.ctrName;
	}

	public void setCtrName(String ctrName) {
		this.ctrName = ctrName;
	}

	@Column(name = "CON_ID")
	public Integer getConId() {
		return this.conId;
	}

	public void setConId(Integer conId) {
		this.conId = conId;
	}

	@Column(name = "CON_NUMBER", length = 50)
	public String getConNumber() {
		return this.conNumber;
	}

	public void setConNumber(String conNumber) {
		this.conNumber = conNumber;
	}

	@Column(name = "CON_DATE", length = 10)
	public Date getConDate() {
		return this.conDate;
	}

	public void setConDate(Date conDate) {
		this.conDate = conDate;
	}

	@Column(name = "SPC_ID")
	public Integer getSpcId() {
		return this.spcId;
	}

	public void setSpcId(Integer spcId) {
		this.spcId = spcId;
	}

	@Column(name = "SPC_NUMBER", length = 50)
	public String getSpcNumber() {
		return this.spcNumber;
	}

	public void setSpcNumber(String spcNumber) {
		this.spcNumber = spcNumber;
	}

	@Column(name = "SPC_DATE", length = 10)
	public Date getSpcDate() {
		return this.spcDate;
	}

	public void setSpcDate(Date spcDate) {
		this.spcDate = spcDate;
	}

	@Column(name = "SPC_SUMM", precision = 15)
	public BigDecimal getSpcSumm() {
		return this.spcSumm;
	}

	public void setSpcSumm(BigDecimal spcSumm) {
		this.spcSumm = spcSumm;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DclUnclosedSpecVId))
			return false;
		DclUnclosedSpecVId castOther = (DclUnclosedSpecVId) other;

		return ((this.getCtrId() == castOther.getCtrId()) || (this.getCtrId() != null
				&& castOther.getCtrId() != null && this.getCtrId().equals(
				castOther.getCtrId())))
				&& ((this.getCtrName() == castOther.getCtrName()) || (this
						.getCtrName() != null
						&& castOther.getCtrName() != null && this.getCtrName()
						.equals(castOther.getCtrName())))
				&& ((this.getConId() == castOther.getConId()) || (this
						.getConId() != null
						&& castOther.getConId() != null && this.getConId()
						.equals(castOther.getConId())))
				&& ((this.getConNumber() == castOther.getConNumber()) || (this
						.getConNumber() != null
						&& castOther.getConNumber() != null && this
						.getConNumber().equals(castOther.getConNumber())))
				&& ((this.getConDate() == castOther.getConDate()) || (this
						.getConDate() != null
						&& castOther.getConDate() != null && this.getConDate()
						.equals(castOther.getConDate())))
				&& ((this.getSpcId() == castOther.getSpcId()) || (this
						.getSpcId() != null
						&& castOther.getSpcId() != null && this.getSpcId()
						.equals(castOther.getSpcId())))
				&& ((this.getSpcNumber() == castOther.getSpcNumber()) || (this
						.getSpcNumber() != null
						&& castOther.getSpcNumber() != null && this
						.getSpcNumber().equals(castOther.getSpcNumber())))
				&& ((this.getSpcDate() == castOther.getSpcDate()) || (this
						.getSpcDate() != null
						&& castOther.getSpcDate() != null && this.getSpcDate()
						.equals(castOther.getSpcDate())))
				&& ((this.getSpcSumm() == castOther.getSpcSumm()) || (this
						.getSpcSumm() != null
						&& castOther.getSpcSumm() != null && this.getSpcSumm()
						.equals(castOther.getSpcSumm())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getCtrId() == null ? 0 : this.getCtrId().hashCode());
		result = 37 * result
				+ (getCtrName() == null ? 0 : this.getCtrName().hashCode());
		result = 37 * result
				+ (getConId() == null ? 0 : this.getConId().hashCode());
		result = 37 * result
				+ (getConNumber() == null ? 0 : this.getConNumber().hashCode());
		result = 37 * result
				+ (getConDate() == null ? 0 : this.getConDate().hashCode());
		result = 37 * result
				+ (getSpcId() == null ? 0 : this.getSpcId().hashCode());
		result = 37 * result
				+ (getSpcNumber() == null ? 0 : this.getSpcNumber().hashCode());
		result = 37 * result
				+ (getSpcDate() == null ? 0 : this.getSpcDate().hashCode());
		result = 37 * result
				+ (getSpcSumm() == null ? 0 : this.getSpcSumm().hashCode());
		return result;
	}

}
