package net.sam.dcl.dbo.dirty;

// Generated 23-May-2007 22:53:40 by Hibernate Tools 3.2.0.b9

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * DclUnclosedSpecV generated by hbm2java
 */
@Entity
@Table(name = "DCL_UNCLOSED_SPEC_V")
public class DclUnclosedSpecV implements java.io.Serializable {

	private DclUnclosedSpecVId id;

	public DclUnclosedSpecV() {
	}

	public DclUnclosedSpecV(DclUnclosedSpecVId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides( {
			@AttributeOverride(name = "ctrId", column = @Column(name = "CTR_ID")),
			@AttributeOverride(name = "ctrName", column = @Column(name = "CTR_NAME", length = 50)),
			@AttributeOverride(name = "conId", column = @Column(name = "CON_ID")),
			@AttributeOverride(name = "conNumber", column = @Column(name = "CON_NUMBER", length = 50)),
			@AttributeOverride(name = "conDate", column = @Column(name = "CON_DATE", length = 10)),
			@AttributeOverride(name = "spcId", column = @Column(name = "SPC_ID")),
			@AttributeOverride(name = "spcNumber", column = @Column(name = "SPC_NUMBER", length = 50)),
			@AttributeOverride(name = "spcDate", column = @Column(name = "SPC_DATE", length = 10)),
			@AttributeOverride(name = "spcSumm", column = @Column(name = "SPC_SUMM", precision = 15)) })
	public DclUnclosedSpecVId getId() {
		return this.id;
	}

	public void setId(DclUnclosedSpecVId id) {
		this.id = id;
	}

}
