package net.sam.dcl.dbo.dirty;

// Generated 23-May-2007 22:53:40 by Hibernate Tools 3.2.0.b9

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DclUserLanguageId generated by hbm2java
 */
@Embeddable
public class DclUserLanguageId implements java.io.Serializable {

	private int usrId;

	private int lngId;

	public DclUserLanguageId() {
	}

	public DclUserLanguageId(int usrId, int lngId) {
		this.usrId = usrId;
		this.lngId = lngId;
	}

	@Column(name = "USR_ID", nullable = false)
	public int getUsrId() {
		return this.usrId;
	}

	public void setUsrId(int usrId) {
		this.usrId = usrId;
	}

	@Column(name = "LNG_ID", nullable = false)
	public int getLngId() {
		return this.lngId;
	}

	public void setLngId(int lngId) {
		this.lngId = lngId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DclUserLanguageId))
			return false;
		DclUserLanguageId castOther = (DclUserLanguageId) other;

		return (this.getUsrId() == castOther.getUsrId())
				&& (this.getLngId() == castOther.getLngId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getUsrId();
		result = 37 * result + this.getLngId();
		return result;
	}

}
