package net.sam.dcl.dbo.dirty;

// Generated 23-May-2007 22:53:40 by Hibernate Tools 3.2.0.b9

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DclYearNumId generated by hbm2java
 */
@Embeddable
public class DclYearNumId implements java.io.Serializable {

	private int dclYear;

	private String dclTable;

	public DclYearNumId() {
	}

	public DclYearNumId(int dclYear, String dclTable) {
		this.dclYear = dclYear;
		this.dclTable = dclTable;
	}

	@Column(name = "DCL_YEAR", nullable = false)
	public int getDclYear() {
		return this.dclYear;
	}

	public void setDclYear(int dclYear) {
		this.dclYear = dclYear;
	}

	@Column(name = "DCL_TABLE", nullable = false, length = 64)
	public String getDclTable() {
		return this.dclTable;
	}

	public void setDclTable(String dclTable) {
		this.dclTable = dclTable;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DclYearNumId))
			return false;
		DclYearNumId castOther = (DclYearNumId) other;

		return (this.getDclYear() == castOther.getDclYear())
				&& ((this.getDclTable() == castOther.getDclTable()) || (this
						.getDclTable() != null
						&& castOther.getDclTable() != null && this
						.getDclTable().equals(castOther.getDclTable())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getDclYear();
		result = 37 * result
				+ (getDclTable() == null ? 0 : this.getDclTable().hashCode());
		return result;
	}

}
