package net.sam.dcl.dbo.dirty;

// Generated 23-May-2007 22:53:40 by Hibernate Tools 3.2.0.b9

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * DclYearNum generated by hbm2java
 */
@Entity
@Table(name = "DCL_YEAR_NUM")
public class DclYearNum implements java.io.Serializable {

	private DclYearNumId id;

	private int dclNum;

	public DclYearNum() {
	}

	public DclYearNum(DclYearNumId id, int dclNum) {
		this.id = id;
		this.dclNum = dclNum;
	}

	@EmbeddedId
	@AttributeOverrides( {
			@AttributeOverride(name = "dclYear", column = @Column(name = "DCL_YEAR", nullable = false)),
			@AttributeOverride(name = "dclTable", column = @Column(name = "DCL_TABLE", nullable = false, length = 64)) })
	public DclYearNumId getId() {
		return this.id;
	}

	public void setId(DclYearNumId id) {
		this.id = id;
	}

	@Column(name = "DCL_NUM", nullable = false)
	public int getDclNum() {
		return this.dclNum;
	}

	public void setDclNum(int dclNum) {
		this.dclNum = dclNum;
	}

}
