-- Firebird DCL_COUNTRY -> Postgres mapping
-- Firebird generator GEN_DCL_COUNTRY_ID + trigger DCL_COUNTRY_BI0 replaced by identity.
CREATE TABLE dcl_country (
    cut_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cut_create_date TIMESTAMP NOT NULL,
    usr_id_create INTEGER NOT NULL,
    cut_edit_date TIMESTAMP NOT NULL,
    usr_id_edit INTEGER NOT NULL,
    cut_name VARCHAR(50) NOT NULL
);
