-- Firebird DCL_CURRENCY -> Postgres mapping
-- Source: db/Lintera_dcl-5_schema.ddl (DCL_CURRENCY)
-- Firebird generator GEN_DCL_CURRENCY_ID replaced by identity.
CREATE TABLE dcl_currency (
    cur_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cur_name VARCHAR(10) NOT NULL,
    cur_no_round SMALLINT,
    cur_sort_order SMALLINT
);
